### ISSUE TITLE
Responsive Breakpoint iPad

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#100]
@McCouman Ich konnte das Repo nicht finden, in dem du deine Designs entwickelst, daher lade ich die Issues mal hier ab:

Auf dem iPad hat das aktuelle Design noch einen kaputten Breakpoint. Das sollte hier doch eher die volle Breite nutzen finde ich.

![ipad 3 2015 03 30_10](https://cloud.githubusercontent.com/assets/144173/6946550/6a5b0958-d8a1-11e4-9719-d2c1b1512d74.PNG)

**Comment by McCouman** [comment]
Danke hatte ich ja schon einmal früher gefixed. 
Das liegt daran, das die Einbindungen des fixes nicht über den Firtz laufen, sondern unabhängig verliefen. Daher sind die Änderungen auch nicht enthalten. 

Ich nehme es mit auf!

**Comment by McCouman** [comment]
fixed
![bildschirmfoto 2015-04-04 um 02 18 22](https://cloud.githubusercontent.com/assets/3239082/6990626/f02932be-da70-11e4-8c62-e619274050bb.png)
