### ISSUE TITLE
Design: Volle Breite auf Smartphones nutzen

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#101]
Ich hatte das schon auf Twitter angesprochen: Was haltet ihr davon hier die volle Breite des Schirms auszunutzen? Ich finde rechts und links von einem Post ist doch recht viel Margin.

![mostly harmless 2015 03 31_0](https://cloud.githubusercontent.com/assets/144173/6946608/e095bab4-d8a1-11e4-9e2b-1bd3577df085.PNG)

**Comment by McCouman** [comment]
Hi das ist ein peeding: 15. Und ja es geht so nen bissel. Muss ich mal schauen. Eigentlich habe ich es absichtlich so gemacht. Da die breadcrumb sonst besch*** aussieht.

Mal schauen, vielleicht bastel ich mal und können dann gemeinsam festhalten, was besser ist?

**Comment by McCouman** [comment]
fixed
![bildschirmfoto 2015-04-04 um 02 13 01](https://cloud.githubusercontent.com/assets/3239082/6990610/49f82a12-da70-11e4-9189-aa2c6c678430.png)
