### ISSUE TITLE
Suche als Extension

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#102]
Gibt es einen Grund, warum die Suche nicht als Extension realisiert ist? Kann ja schon vorinstalliert sein, aber so lässt sich das später alles besser anpassen.

**Comment by eazyliving** [comment]
Dafür gibt es einen noch recht blöden Grund: Eine Extension ändert entweder den kompletten Output einer Seite/eines Feeds, übernimmt also die komplette Ausgabe. Oder aber sie ändert die Ausgabe einer Episode, einer bestimmten Einheit.

Die SuFu ändert aber eigtl nicht die Ausgabe in ihrer Form, nur im Umfang. Und das geht außerhalb des Hauptcodes im Moment nicht sauber. Es ginge irgendwie, aber nicht schön. Und so lange ich die Extensions da nicht noch weiter aufbohre (firtz 3.0 ;)) bleibt das vermutlich auch so :)

Was lässt sich denn besser anpassen? Das Entfernen der SuFu?

**Comment by i42n** [comment]
Ja, ich habe da primär ans Entfernen/Hinzufügen der Suchfunktion gedacht. Oder eben auch ans Ersetzen durch eine "eigene" Suchfunktion. Geht einfach generell darum, dass ein modularer Aufbau in Zukunft(tm) eine Menge Arbeit sparen kann, wenn man bestimmte Teile neu/anders machen möchte.

**Comment by eazyliving** [comment]
Ja, schon. Das ist auch der Grund, weshalb ich beim 2er so viel Wert auf den Ausbau der Extensions gelegt habe. Das entlastet den Kern auch davon, ständig Updates zu bekommen bei tollen neuen Entwicklungen und Ideen.

Wie schon woanders geschrieben: Ich schau mir das noch einmal genauer an. Vielleicht hab ich ja doch eine gute Idee...

**Comment by eazyliving** [comment]
Das wäre dann ja jetzt erledigt, was? :)
