### ISSUE TITLE
Contributor auf der Archiv Seite ausgeben

### ISSUE THREAD

**Issue by McCouman** [eazyliving/firtz#103]
Hi  @eazyliving 

ich habe mich noch nicht wirklich mir dem Framework vertraut gemacht. Wie kann ich den die Ausgaben der Extensions einbinden. 

Also einzeln ausgeben und nicht über:
<pre>
&lt;check if="{{isset(@item.append)}}">
{{@item.append | raw}}
&lt;/check>
</pre>

Ich würde gerne wie bei Tim auf der <a href="http://cre.fm/archiv">CRE</a> erstellen wollen. 
Da ich den Ansatz eigentlich richtig finde.

Funzt aber irgend wie nicht auf der Archiv Seite.

**Comment by McCouman** [comment]
Auch würde mich Interessieren, wie man Anzahl der gesamten Episoden auf dem Archiv ausgeben kann? Siehe Idee =>http://firtz.wikibyte.org/-/show/page/Archiv/Archiv

**Comment by eazyliving** [comment]
Zum "Vertrautmachen" müsste ja auch die Doku, die ich für die Extensions ja gerade erst angefangen habe fertig sein. Ist also meine Schuld :) 

Die gibt's übrigens hier: https://github.com/eazyliving/firtz/blob/quorx/doc/extensions.md

Generell: Um den Ansatz von Podlove komplett auszufüllen, müssten es nicht nur Contributoren sein, sondern auch Rollen. Die gibt's aber (bisher noch) nicht. Ich bin auch zunächst nicht der Meinung, dass ich die gerne hätte, denn es fügt wieder einen Level an Komplexität hinzu, den ich im firtz eigentlich nicht haben möchte. 

Ich lasse mich da aber auch überstimmen, denn es ist ja eine Extension und betrifft damit nicht den Kern des firtzens :)

Aber zur Ausgangsfrage zurück. Es wird jetzt etwas... naja, komplex ist das falsche Wort. Länglich? :)

Die Contributoren stehen in jeder Episode im .epi (oder auch im json mittels "_contributors:..."). Nehmen wir an, da steht "eazy mccouman". Der firtz sucht nun im Pfad /ext/contributors/data/ nach einer Datei namens eazy.cfg und nach einer namens mccouman.cfg.

Findet er die, entnimmt er der Datei die Daten für allerlei Kram. Richtiger Name, twitter, Mail etc...

Diese Daten landen dann am Ende in einem Array für jede Episode (die ja in $item im loop untergebracht ist):

```
$item['contributors_data'][$con]
```

$con ist dann der slug des jeweiligen Contributors, z.B. "eazy". Im normalen Loop der Webseite habe ich dann z.B. sowas im template (unter /ext/contributors/episode/contributors_episode.html):

```
<check if="{{isset(@item.contributors_data)}}">
<h2>{{@dict_contributors}}</h2>
	<repeat group="{{@item.contributors_data}}" value="{{@con}}" key="{{@nick}}">
		<p>
		{{@con.name}}<br>
		<check if="{{isset(@con.twitter)}}">
			<a class="uk-button" href="https://twitter.com/{{@con.twitter}}"><span class="fa fa-twitter"></span></a>
		</check>
		<check if="{{isset(@con.adn)}}">
			<a class="uk-button" href="https://alpha.app.net/{{@con.adn}}"><span class="fa fa-adn"></span></a>
		</check>
		<check if="{{isset(@con.mail)}}">
			<a class="uk-button" href="mailto:{{@con.mail}}"><span class="fa fa-envelope"></span></a>
		</check>
		<check if="{{isset(@con.url)}}">
			<a class="uk-button" href="{{@con.url}}"><span class="fa fa-globe"></span></a>
		</check>
		
		<check if="{{isset(@con.flattr)}}">
			<iframe src="http://api.flattr.com/button/view/?user_id={{@con.flattr}}&amp;url={{@item.flattrlink | raw}}/{{@nick}}&amp;title={{@item.flattrtitle | raw}}&amp;popout=0&amp;button=compact" class="FlattrButton" width="110" height="20" frameborder="0" scrolling="no" border="0" marginheight="0" marginwidth="0" allowtransparency="true"></iframe>
		</check>
		</p>
	</repeat>
</check>
```
Ich sehe gerade, dass ich im template-Schnippsel @con anders nutze als vorher im php mit $con. @con ist an der Stelle der Inhalt des Arrays für den Contributor @nick. Ich werde das bei Gelegenheit glatt ziehen.

Möchtest Du also auf die Contributoren zugreifen, ist 'contributor_data' das, was Du suchts :)

**Comment by eazyliving** [comment]
Achso... in die .cfg kann man eigtl reinschreiben was man möchte. Es muss nur eben key:value sein. Und es sollte dann auch im template genutzt werden. Sollte also irgendwann mal irgendein tolles neues Netzwerk namens "schnurz" entstehen, müsst Ihr das nur in die cfg und das template anfügen: voila :)

**Comment by McCouman** [comment]
Hat funktioniert! 

Danke :)
