### ISSUE TITLE
Frage: Publikation in der Zukunft und Datumsformat fürs Tag

### ISSUE THREAD

**Issue by chrismarquardt** [eazyliving/firtz#105]
Frage zur Doku. Du schreibst, dass man im Firtz/Auphonic-Zusammenspiel durch das Tag

_date:2014-12-12 20:15:00

in der Auphonic-Produktion den Publishing-Zeitraum steuern kann. 

1. Verstehe ich das recht? Firtz publisht die Episode erst, wenn das entsprechende Datum erreicht ist?

2. Das Datumsformat ist unklar. Ich vermute Du meinst YYYY-MM-DD HH:MM:SS aber das in der Doku verwendete Beispiel 2014-12-12 gibt die Unterscheidung von Monat und Tag leider nicht her. Bitte um Klärung.

**Comment by eazyliving** [comment]
Oops :)

Zunächst: Ja, das ist so. Wenn das Datum in der Zukunft liegt, unterdrückt firtz das so lange.
Und ja, das ist unklar. Es ist natürlich YYYY-MM-DD HH:MM:SS. Ich ändere das mal :)

**Comment by chrismarquardt** [comment]
Danke!
