### ISSUE TITLE
Impressum als Seite - wie aus dem Menü verbannen?

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#109]
Ich habe aktuell mein Impressum als eigene Seite angelegt. Deshalb taucht sie im Menü oben auf. Ich hätte das aber lieber nicht im Menü, sondern nur als Link im Footer.

Gibt es eine elegante Möglichkeit das zu tun?

**Comment by McCouman** [comment]
Siehe Lösungsansätze <a href="https://github.com/eazyliving/firtz/issues/106">hier</a>

Vielleicht kann man da noch ein Art "hidden" in den Loop basteln, damit dieses Seiten nicht ausgelesen werden oder was weis ich.

Gefällt mir auch noch nicht.

**Comment by McCouman** [comment]
Fixed!

Ich habe mich für den Ordner "legal" entschieden. 
=> <code>/templates/default/pages/legal/</code>

Alles was da rein fällt, wird am Ende nur im Footer ausgegeben.

Siehe Header Tabs und Footer: http://firtz.wikibyte.org/QuorXII-Standard/show

**Comment by eazyliving** [comment]
Lass mich das mal überdenken damits konstant und sauber ist. 

Ich glaube, pages/head bzw /footer wäre vermutlich sauberer. 

--
Gruß,
Christian Bednarek

**Comment by i42n** [comment]
> Ich glaube, pages/head bzw /footer wäre vermutlich sauberer. 

Sehe ich auch so.

**Comment by McCouman** [comment]
Ok ändere ich ab :)

**Comment by eazyliving** [comment]
Und wenn ich den legal-Kram lieber im Kopfmenü hab? Da will ich's bei mir jedenfalls haben. Fuß zusätzlich gerne, aber solch Zeug gehört mMn ganz oben hin :)

**Comment by eazyliving** [comment]
Aber noch was... Mit der aktuellen Version wird das sowieso nur bedingt gehen. Ich sehe da noch ein ganz anderes Ding. Fangen wir vorne an:

1. Alles im Ordner pages/* wird oben in der Menüleiste angezeigt. Seiten in pages (*.html) werden direkt ins Menü eingefügt, Ordner als Dropdown mit den Dateien dort drin als Menüpunkte.

2. Alles in header/* head/* episode/* sidebar/* footer/* wiederum wird direkt an den jeweiligen Stellen inkludiert. 

Soviel dazu. Pages werden also bisher nur im Kopf der Seite angezeigt. Nun fügen wir neue Orte hinzu. Oben, unten, an der Seite, was auch immer... head, foot, side...

Nun gibt's in pages einen Ordner legal oder auch footer... was passiert? :) Genau, es wird oben im Menü unter "footer" angezeigt. 

Lasst mich mal drüber meditieren. Vielleicht hab ich da noch eine gute Idee.

**Comment by McCouman** [comment]
Huh... bin gespannt.

Jedoch ging es mir eher um die url, die mir vom Aufbau im Firtz sehr sehr gut gefällt. Da der Linkaufbau, schon fast wie eine pseudo Programmiersprache wirkt :)

Bsp.: 

<code>&lt;http&#58;//meine-domain.tld>/&lt;feedname>/show/page/Kukuk</code>

Ausgesprochen:

<code>He **Meine Domain** gehe mal zum **Feedname** und **schaue** auf die **Seite**: **Kukuk**</code>

mit dem Ordner "legal": 

<code>&lt;http&#58;//meine-domain.tld>/&lt;feedname>/show/page/legal/Impressum</code>

<code>He **Meine Domain** gehe mal zum **Feedname** und **schaue** in den **Seiten** unter **rechtliches** da will einer das **Impressum**</code>

mit dem Ordner "footer": 

<code>&lt;http&#58;//meine-domain.tld>/&lt;feedname>/show/page/footer/Impressum</code>

<code>He **Meine Domain** gehe mal zum **Feedname** und **schaue** bei den **Seiten** und schieße dir dabei mal in den **Fuß**, dann brauchst Du ein **Impressum**</code> - das ist doch ähhh :D 

****
OK - Quatsch bei Seite:

Wenn du die Pages "Impressum" oben haben willst, dann lass einfach den "Ordner footer" weg. Das ist doch einfacher, als noch nen Ordner: Head dazu zu ballern? - Oooder ich habe Deine Idee einfach noch nicht verstanden (letzteres passiert mir ständig! Vor allem wenn mir einige Damen etwas... lassen wi'r das.)

**Comment by eazyliving** [comment]
Nur kurz zum Ort des Impressums: Da gibt's mWn schon Urteile, die davon ausgehen, dass man für's Impressum nicht scrollen (jedenfalls nicht stundenlang...) müssen sollte. 

Aber wir werden uns hier nun wohl nicht in rechtliche Diskussionen verstricken ;) 

Das mit dem "legal" im Pfad ist ja auch erstmal echt hübsch. Ich werde aber nicht gut damit leben können, Ordner mal nach ihrer Lokation (head/footer/sidebar) zu benennen und ein anderes Mal nach der Funktion (legal eben). 

In einer alkoholinduziert kreativen Nacht könnte man darüber nachdenken, ein getrenntes Konzept zu erstellen: Erstmal Ordner nach Funktion benennen (legal/menu/donation/subscribe you name it) und diese Funktionen dann Orten zuordnen (head/sidebar/footer).

Damit könnten Extensions, die Ausgaben wie z.B. paypal-Buttons oder Impressen erzeugen erst einmal eine Funktion zur Verfügung stellen und erst das Template selbst bestimmt dann, ob z.B. paypal in der Sidebar oder im Fuß landet...

Das wäre aber eher was, das in Richtung firtz 3.0 geht :) 

Hm... je mehr ich drüber nachdenke, desto besser gefällt es mir :)

**Comment by McCouman** [comment]
3.0 halte ich für ssseeehr gut Idee :D
