### ISSUE TITLE
Welche Extensions in die Distribution?

### ISSUE THREAD

**Issue by eazyliving** [eazyliving/firtz#111]
Hallo Leute,

ich brauch mal Eure Hilfe.

Der 2te firtz hat ja nun ein nettes Extensionsystem und schon einen feinen Grundstock an Erweiterungen, die mal mehr, mal weniger interessant für die Masse ist.

Die Frage, die ich mir stelle ist folgende:
Welche der bisher vorhandenen Extensions nehme ich in den Kanon auf? Welche kommen mit der Grundinstallation daher?

Ich liste mal auf und schreibe mit +/- meine Meinung dahinter:

adnthread -
atom -
breadcrumb +
contributors -
disqus -
embed +
podtrac - 
search +
shariff -

Was meint Ihr?

**Comment by McCouman** [comment]
breadcrumb ist nicht von sehr vielen erwünscht oder häufig störend, deshalb habe ich Sie auch als extension gemacht. Meist nutzt das nur "etwas unbedarften Lesern/hörern" und fand es persönlich wichtig sie in einem Firtz vorzufinden. Muss jedoch nicht standard sein.

sharif finde ich an sich ne nette Idee, jedoch habe ich die Extension nicht ganz verstanden, da der Player das ja schon standard dabei hat. An sonsten würde ich echer disqus als standard sehen. Da so der Eindruck eines "normalen Blogsystems" erkenntlich wird. Wer etwas anderes will, kann es ja löschen. Jedoch wäre es von der möglichen "Akzeptanz" der Masse, eher Sinnvoll sie mit hinein zu nehmen.

**Comment by eazyliving** [comment]
Urgs. Stimmt, der Player hat da social Kram. Ist das ohne Tracking?

**Comment by McCouman** [comment]
Das müssten wir Podlove fragen! Ike weesit och net.
In übrigen gibt es noch die <a href="https://github.com/McCouman/quorx2.0_documentation/tree/master/ext/demo-sidebars">demo-sidebars</a> die der @i42n wollte. 

=> https://github.com/McCouman/quorx2.0_documentation/tree/master/ext

**Comment by eazyliving** [comment]
Laut podlove sind die buttons tracksave. Also wird shariff aus dem Kanon geholt.

**Comment by McCouman** [comment]
Sollte als Extension meiner Meinung jedoch erhalten bleiben!?

**Comment by eazyliving** [comment]
Ja aber sicher!
