### ISSUE TITLE
Feed Image via HTTPS

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#112]
Aktuell wirft meine Seite noch https Fehler, da nicht alle Inhalte via https ausgeliefert werden. Das liegt vor allem am Feed Image: https://github.com/eazyliving/firtz/blob/911f7819f167d5258df8b57ada0b62905e09cae6/feeds/demo/feed.cfg#L21

Ich habe versucht das durch https zu ersetzen. Im Grunde geht das. Aber der Feed ist dann nicht mehr valide, da iTunes im Feed irgendwie kein https haben will für die Bilder. Sehr seltsam alles.

Habe wieder zurück auf http gestellt. Wollte das aber hier nur mal fallen lassen, dass das irgendwie noch Probleme macht.

**Comment by eazyliving** [comment]
Das Problem haben auch andere: https://sendegate.de/t/https-feed-in-itunes-directory-eintragen-zertifikatsproblem/1035/3

**Comment by McCouman** [comment]
Was wohl auch eher ein Problem von Apple ist? So habe ich jetzt verstanden, das Apple zwar https feeds nimmt jedoch nur links mit http ausliest. Da die meisten iTunes als Verzeichnis ausliest...
