### ISSUE TITLE
Wir müssen über Bilder sprechen

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/firtz#113]
Bilder zur Folge sind irgendwie wichtig. Wie kriegen wir das in den Firtz?

http://youtu.be/R5Y_6OXFqB0

**Comment by McCouman** [comment]
Idee dazu habe ich hier zusammen gebracht 
=> Demo: http://firtz-design.wikibyte.org/Q2-demo-player-transparent-black/show

Quatschen hier: https://sendegate.de/t/ppw15a-doku-das-perfekte-episodenbild/1360/3

**Comment by eazyliving** [comment]
Können wir darüber in der 2.1 sprechen? :)

**Comment by McCouman** [comment]
jo => twitter :)

**Comment by McCouman** [comment]
wird in der RC 3 kommen
