### ISSUE TITLE
Besseres Error-Handling bei nichtexistierenden Episoden-URLs

### ISSUE THREAD

**Issue by schulle4u** [eazyliving/firtz#116]
Mir ist grad mal aufgefallen, dass sich der Firtz recht einfach zum Ausspucken von PHP-Fehlern bringen lässt. Ruft man eine Show-URL auf, die (noch) nicht existiert, erhält man eine zwar korrekte, aber etwas "erschreckende" Fehlermeldung zurück. 

```
Internal Server Error
Undefined index: xyz
• src/classes/feed.php:649 Base->{closure}()
• index.php:390 feed->renderHTML()
• src/lib/base.php:1422 Base->call()
• index.php:738 Base->run()
```

Ein einfaches "gibts nich" wäre hier imho etwas aussagekräftiger und untergräbt dann auch nicht die Setups, bei denen das PHP-Error-Reporting ausgeschaltet sein sollte. :)

**Comment by eazyliving** [comment]
Ich entschuldige mich aufrichtig dafür, dass das so lange gedauert hat. Ich hab's schlicht verpeilt :-(
Und sollte nun natürlich gefixt sein.

**Comment by schulle4u** [comment]
Besser spät als nie, wobei ich dieses Issue sogar völlig vergessen hatte. Vielen Dank, werde das in nächster Zeit mal testen. :)

Steffen
