### ISSUE TITLE
font-awesome gets called per http:// which breaks icons on https sites

### ISSUE THREAD

**Issue by chrismarquardt** [eazyliving/firtz#117]
Please change calls to external resources like font-awesome to https, so they show up on https sites.

**Comment by eazyliving** [comment]
fixed!

**Comment by 55dmb** [comment]
Hi - I’m needing help with a different issue altogether and can’t find another way to reach you. I noticed your posts on the bither git site, and really need help with sending funds from my HD Account. If I try to move to the hot or cold wallets then they just sit there without confirming. If I try to send directly from hd to - for example - to another wallet or address. Let’s say I want to send to a BitPay address, the transaction will sit...and sit...and sit without broadcasting to the Blockchain (is this a testnet vs main net issue?). The HD account seems to act like it is a ‘Watch only’ account. If so, then how do I even move it to the hot wallet or cold wallet? On the bither p2p network it shows that I have 2.3 Bitcoins, but if I seed the hd account to a different wallet then it will show that I have only 0.02 available. I’m having a difficult time with the developer support, and will happily give a reward of 0.1 BTC if you know how to fix it.
