### ISSUE TITLE
Kleine Info:  Color Design für den Webplayer

### ISSUE THREAD

**Issue by McCouman** [eazyliving/firtz#67]
Habe da mal ein wenig herumgespielt und dem Design + Webplayer eine Farbe gegeben. 

da: https://github.com/McCouman/firtz-designs

und hier (noch) live:

http://suche.wikibyte.org

Ich weis nicht ob das nicht auch besser geht, um die Farben ins Spiel zu bekommen: 

https://github.com/McCouman/firtz-designs/blob/master/firtz/feeds/night/feed.cfg#L60

Grüße M.C.

**Comment by eazyliving** [comment]
Das wird die Tage wohl überflüssig. Oder anders laufen müssen :)
