### ISSUE TITLE
Suchleiste via DuckDuckGo

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#81]
Was hältst du von der Idee die DuckDuckGo Suchleiste einzubauen? So könnte man eine einfache Suchfunktion anbieten.

https://duckduckgo.com/search_box

**Comment by eazyliving** [comment]
Was ich noch nicht verstehe: Wo ist denn nun die Suchleiste? Bin ich blöde?
Ich würde die Extension gerne ins Repository aufnehmen. Als schönes Beispiel und als nützliches obendrein.

**Comment by Reisen-Wandern-Tauchen** [comment]
Hi,
ha! Jetzt weiß ich was ich in der Doku übersehen habe!
Um eine Suche per "Suchleiste" einzubauen, müsste man noch ein kleines "Formular" mit dem entsprechenden Input-Feld einbinden, welchdes dann die Afrage via GET (eigentlich müsste auch PUT funktionieren, hab ich aber nicht getestet) weitergibt.
Meine erste Implementierung sieht vor, dass die Keywords / Tags unterhalb des Artikels gelistet werden und man per Klick die Abfrage ausführen kann. 
(es werden wie gesagt momentan auch ausschließlich die Keywords / Tags untersucht, aber nicht Titel und Artikeltext - obwohl sich das vermutlich leicht erweitern lässt; mal schauen ob ich die Tage mal ein wenig Zeit dazu finde...)

Aber das Suchfeld werde ich gleich mal in die Doku mit aufnehmen.
Danke für den Hinweis!

**Comment by Reisen-Wandern-Tauchen** [comment]
Sodale... ein erster Entwurf für die Suchleiste ist gefunden. :-)
Folgender Code kann dafür im Template eingebaut werden:
```html
<form id="tagsearch" action="" method="get" onSubmit="if (document.getElementById('search_input').value != '') { document.getElementById('tagsearch').action = '/{{@feedattr.slug}}/tags/' + document.getElementById('search_input').value + '/'; return true; } alert('leere Sucheingabe'); false;">
	<input type="search" id="search_input" />
</form>
```
Ich musste das im ersten Schritt via JavaScript implementieren, da mir auf die schnelle keine bessere Lösung für die Auflösung des Argument-Strings eingefallen ist.
Eventuell werde ich da noch einen entsprechenden Code in die Extension einbauen, damit diese auch mit GET-Abfragen umgehen kann. POST-Anweisungen werden offensichtlich vom Firtz geblock. Jedenfalls bekomme ich eine entsprechende Meldung, dass diese nicht erlaubt sind... :-)

**Comment by i42n** [comment]
Ich fände es gut, wenn die Tagsearch Suchleiste nicht Default wird bzw. in der Config an- und ausschaltbar wäre. Ich habe meine Tags überhaupt nicht gepflegt und daher wäre bei mir die Tagsuche relativ nutzlos.

**Comment by McCouman** [comment]
Ich fände nen ajax callback für so eine Suche (tags + search) ganz gut. So was in Richtung
=> http://suche.podbe.de/ (zum testen vielleicht: "podunion" eingeben)

Vielleicht kann man ja die API von DuckDuckGo (wenn die so etwas haben, noch nicht nachgeschaut!) gleich mit abzapfen und damit beides vereinen?

Nur so als Idea :)

**Comment by eazyliving** [comment]
Also... ich hab das mal ganz anders gemacht :)
Es gibt im 2er firtz eine keywordsuche, die kommt allerdings ohne duckduckgo oder sonst irgendeiner Suchmaschine aus.

Könnt Ihr Euch auf 

http://et.enif.uberspace.de/ oder auch (das ist ein Testsystem, kein Editing) auf http://quorx.firtz.org/demo/show/

**Comment by i42n** [comment]
Woher nimmt die Suche die "Keywords"?

**Comment by eazyliving** [comment]
Aus den... Keywords ;). Die kann Mannen die epi schreiben oder in die auphonic Produktion 

--
Gruß,
Christian Bednarek

**Comment by McCouman** [comment]
Toll Toll Supertoll !
