### ISSUE TITLE
map - http-error 500 (illegal string offset 'latitude')

### ISSUE THREAD

**Issue by Reisen-Wandern-Tauchen** [eazyliving/firtz#84]
Hi,

habe mir heute den aktuellen Stand aus dem Repository geholt und getestet.
Dabei sprang mir (als Outdoor-Podcaster) natürlich auch gleich das Map-Feature ins Auge, das ja jetzt prinzipiell im Firtz! eingebaut ist.

Beim Aufruf der Map (mittels http://podcast-url//feed/map) bekam ich allerdings leider keine Karte angezeigt sondern einen HTTP-Fehler 500 (internal server error) mit dem Hinweis auf einen "illegal string offset 'latitude"). (obowohl es eine Episode mit Koordinaten-Angaben im Auphonic-File gibt)
Nach einigem Hin- und Herprobieren zur Eingrenzung des Fehlers stellte sich das Ganze für mich so dar:

in der /classes/episode.php werden in der Auswerwertung des Auphonic-Files erst die die $item['location']['latitude'] und dann auch gleich die $item['location']['longitude'] auf 0 gesetzt (wohlgemerkt als Zahl und nicht als Zeichenfolge).
Dann folgt die Abfrage, ob die Koordinaten im Auphonic-File gesetzt sind. Und wenn ja, werden die entsprechenden Koordinaten eingetragen. Hier liegt dann auch das erste Problem. Die Abrfage folgt auf !='null' - in der Auphonic-Datei wird aber nicht der String 'null' gespeichert, sondern null als Wert (also leer)
Offensichtlich hat dann die PHP-Routine in der /templates/map.html genau damit das Problem. Weil dort die Abfrage auf !=0 geht, aber die Variablen eben nicht auf 0 sondern gesetzt sind, sondern leer.
Ändert man diese Abfrage von {{@item.location.latitude!=0}} auf {{isset(@item.location.latitude}} funktioniert die Routine wie vorgesehen und die Karte wird - inkl. Marker - angezeigt.
Ich würde dann auch in der /classes/episode.php auch auf die erste Definition der Variablen auf 0 verzichten und gleich mit isset-Abfragen arbeiten. So werden keine unnötigen Variablen "mitgeschleppt". (kann man aber auch lassen)

Nun habe ich aber noch das Problem, dass mir die "raw.html" fehlt. Was nicht weiter verwunderlich ist, da diese im Repository (noch) nicht enthalten ist. :-)

Zusammengefasst habe ich folgendes gemacht:
**/classes/episode.php**
von
```php
			$item['location']['latitude'] = 0;                                         
                        $item['location']['longitude'] = 0;
			if (isset($prod->metadata->location)) {
			if ($prod->metadata->location->latitude!='null' && $prod->metadata->location->longitude!='null') { 
					$item['location']['latitude'] = $prod->metadata->location->latitude;
					$item['location']['longitude'] = $prod->metadata->location->longitude;
				}
			}
```
auf
```php
			if (isset($prod->metadata->location)) {
				if (isset($prod->metadata->location->latitude) && isset($prod->metadata->location->longitude)) { 
					$item['location']['latitude'] = $prod->metadata->location->latitude;
					$item['location']['longitude'] = $prod->metadata->location->longitude;
				}
			}
```

**/templates/map.html**
von
```html
	  <repeat group="@items" value="@item" key="@key">
	 	 <check if="{{@item.location.latitude!=0}}">
			var myLatlng = new google.maps.LatLng({{@item.location.latitude}},{{@item.location.longitude}});
	  		bounds.extend(myLatlng);
			var marker{{@key}} = new google.maps.Marker({
	      	  icon: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld={{sizeof(@items)-@key}}|FE6256|000000',
			  position: myLatlng,
	       	  map: map,
			  action:  "$('#episode').load('{{@BASEURL}}{{@feedattr.slug}}/raw/{{@item.slug}}')",
	       	  title: '{{@item.title | raw}}'
	  		 });
			
			  var contentString = '<div id="content">'+
		       '<h2 class="firstHeading" class="firstHeading">{{@item.title | raw}}</h1>'+
		       '<div class="bodyContent">'+
		       '<p>'+
			   '{{str_replace(array("\r", "\n"), "", htmlentities(@item.summary,ENT_QUOTES))}}</p>'+
			  '<p><a href="{{@BASEURL}}{{@feedattr.slug}}/show/{{@item.slug}}">Episode</a></p>'+
		       '</div>'+
		       '</div>';
			   // 
		       
		   var infowindow{{@key}} = new google.maps.InfoWindow({
		       content: contentString,
			    
		   });
		 
		oms.addMarker(marker{{@key}});
		</check>
		 </repeat>
```
auf
```html
	  <repeat group="@items" value="@item" key="@key">
	 	 <check if="{{isset(@item.location.latitude) && isset(@item.location.longitude)}}">
			var myLatlng = new google.maps.LatLng({{@item.location.latitude}},{{@item.location.longitude}});
	  		bounds.extend(myLatlng);
			var marker{{@key}} = new google.maps.Marker({
	      	  icon: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld={{sizeof(@items)-@key}}|FE6256|000000',
			  position: myLatlng,
	       	  map: map,
			  action:  "$('#episode').load('{{@BASEURL}}{{@feedattr.slug}}/raw/{{@item.slug}}')",
	       	  title: '{{@item.title | raw}}'
	  		 });
			
			  var contentString = '<div id="content">'+
		       '<h2 class="firstHeading" class="firstHeading">{{@item.title | raw}}</h1>'+
		       '<div class="bodyContent">'+
		       '<p>'+
			   '{{str_replace(array("\r", "\n"), "", htmlentities(@item.summary,ENT_QUOTES))}}</p>'+
			  '<p><a href="{{@BASEURL}}{{@feedattr.slug}}/show/{{@item.slug}}">Episode</a></p>'+
		       '</div>'+
		       '</div>';
			   // 
		       
		   var infowindow{{@key}} = new google.maps.InfoWindow({
		       content: contentString,
			    
		   });
		 
		oms.addMarker(marker{{@key}});
		</check>
	  </repeat>
```

**Comment by eazyliving** [comment]
Hallo Christian,

vielen Dank für die viele Arbeit, die Du Dir gemacht hast. Ich habe das mal umgesetzt und hochgeladen. Wenn Du möchstet, könntest Du mal einen Pull machen und testen. Die raw.html ist nun auch dabei :)

**Comment by Reisen-Wandern-Tauchen** [comment]
Hi Christian,

na das ging ja flott! :-)
Werde ich möglichst bald machen und dann wieder bereichten. Eventuell schaffe ich das heute noch. Aber die "Suchleiste" für die tagsearch-extension hat hier mal Vorrang. Ich denke, das ist für mehr Leute interessant. ;-)

**Comment by Reisen-Wandern-Tauchen** [comment]
Hi Christian,

Test erfolgreich durchlaufen!
Zu sehen unter http://individuell-unterwegs.at/iu/map
:-D

Danke!

**Comment by eazyliving** [comment]
Juhuu! Mal sehen, wie die Karte den Wechsel zum quorx übersteht... da wird auch Arbeit anstehen :-}
