### ISSUE TITLE
Wechsel von bootstrap zu quorx als Standardtemplate 

### ISSUE THREAD

**Issue by eazyliving** [eazyliving/firtz#85]
Bisher verlässt sich der firtz auf bootstrap. CSS und HTML sind relativ aufgeräumt, Themes sind austauschbar.

Viele Themes für bootstrap gibt's allerdings nicht, die meisten beschränken sich auf eine Farbänderung. Und so sieht der firtz nach nunmehr zwei Jahren doch etwas dröge aus.

Vor etwas über einem halben Jahr kam dann @McCouman mit [quorx](/McCouman/Firtz-QuorX-Design) daher und ich war ziemlich direkt ziemlich begeistert. Bestaunen könnt Ihr das unter anderem bei [Schall und Rauch](http://schallrauch.hoersuppe.de).

Das Problem ist aber bisher, dass quorx mit einem kompletten firtz daher kommt. Was ja nicht nur unnötig, sondern auch problematisch ist. Wer will schon ständig alle Änderungen mit der Hand nachführen? Keiner.

Um das Problem endgültig zu beheben, habe ich beschlossen, bootstrap in Rente zu schicken und quorx zum Standardtemplate des firtz zu machen. Ich finde, das Template ist gut durchschaubar und leicht änderbar. 

Die Variablen des Templates finden sich im site.html selbst, bisher gibt's dort aber nur die drei Grundfarben des Themes. Sicher wird sich das auf Dauer ändern.

Ich habe schon überlegt, quorx und bootstrap koexistieren zu lassen, den Gedanken aber schnell verworfen. Das würde überladen wirken und die Sache unnötig verkomplizieren. Kurz und gut: wenn alles so gut weiter läuft, wird am WE der quorx ins rep kommen und auch der podlove subscribe button. 

Einwände? Ich weiß: wer am alten Standardtemplate viel geändert hat, wird sich jetzt erstmal ärgern. Alle Arbeit umsonst, wenn man aktuell bleiben möchte. Sorry :-)

**Comment by Reisen-Wandern-Tauchen** [comment]
Die Quorx-Templates hätte ich gerne schon länger mal eingesetzt. Aber genau der Umstand der parallelen Entwicklungsstränge für das Hauptsystem des firtz hat mich davon abgehalten. (wäre wohl etwas kompliziert die beiden Stränge halbwegs brauchbar zusammenzuführen; mit Automatismus ist es da wohl Essig...)
Ich freue mich darauf! :-D

**Comment by McCouman** [comment]
Freue mich natürlich :)

Mittlerweile baue ich das jedoch anders. Einfach den Ordner "Skin". Die site.html dient mir nur noch für die parametric und Abfragen. 

hier mal meine site.html
<pre>
&lt;check if="{{!@showpage}}">
	&lt;true>
		&lt;check if="{{@singlepage==false }}">
			&lt;include href="skin/denuèr/navigation.html"/>
				&lt;!--Frontpage-->
				&lt;include href="skin/denuèr/frontsite.html"/>		
		&lt;/check>
		&lt;check if="{{@singlepage==true }}">
			&lt;include href="skin/denuèr/navigation.html"/>
				&lt;!--Blogpage-->
				&lt;include href="skin/denuèr/blogsite.html"/>
		&lt;/check>
	&lt;/true>
&lt;/check>	
&lt;check if="{{!@showpage}}">
	&lt;false>
		&lt;!--Page-->
		&lt;include href="{{@showpage}}"/>	
	&lt;/false>
&lt;/check>

&lt;!--Footer-->
&lt;include href="skin/denuèr/footer.html"/>
</pre>
Mit einer kleinen Funktion könnte man das sicher auch so basteln, das überprüft wird, welcher Skin aktiviert wurde. So das man einfach den Namen des Skins angibt und fertig is. Die Templates werden dann im "skin" Ordner abgelegt.

... / templates/skin/bootstraps/
... / templates/skin/quorx/ 
... / templates/skin/mein_tolles_design/

So könnte man vielleicht weitere Designs bauen und unabhängig halten.

P.S. bei Schall und Rauch fehlt die Lizenzangabe (siehe footer unten: <License ?> - 2014 Schall und Rauch)

**Comment by eazyliving** [comment]
Fein. Die Skin-Geschichte wollte ich mir zwar für etwas später aufheben, aber eigentlich hast Du recht. Wenn nicht jetzt, wann dann? Wo finde ich denn die aktuellen Quellen zum Quorx?

**Comment by eazyliving** [comment]
Ich werde das alles ein klein wenig anders machen.

Es wird einen Ordner `templates` geben.
In diesem Ordner gibt es ein default-template mit allen benötigten Dateien. Wer das ändern möchte, legt einen neuen Ordner unter dem Ordner `templates` an und wirft dort alle Dateien hinein, die geändert/hinzugefügt werden sollen, also vom default abweichen.

So muss man die rss2.xml nicht mit sich herumschleppen z.B. und ist trotz anderem Template nicht gekniffen, wenn sich am repo was ändert.

Wichtig ist nur, dass die Dateinamen der Haupttemplates bleiben. Also `site.html`, `rss2.xml`etc...

**Comment by McCouman** [comment]
Jo, das Wordpress template, template-child Prinzip^^

**Comment by McCouman** [comment]
the last public theme => https://github.com/McCouman/Firtz-QuorX-Design

**Comment by i42n** [comment]
> Es wird einen Ordner templates geben.
In diesem Ordner gibt es ein default-template mit allen benötigten Dateien. Wer das ändern möchte, legt einen neuen Ordner unter dem Ordner templates an und wirft dort alle Dateien hinein, die geändert/hinzugefügt werden sollen, also vom default abweichen.

Das halte ich für eine sehr gute Lösung.

**Comment by eazyliving** [comment]
@McCouman das letzte public ist aber nicht das, das Du oben erwähnst, oder?

**Comment by McCouman** [comment]
Nein, das ist nur Testweise gewesen und dachte ich werde das irgend wann vielleicht so umsetzen. Weils einfacher ist und mehr Möglichkeiten hat auch die Blogseite mit "ifs" oder "einzeln" zu designen.

**Comment by eazyliving** [comment]
Es geht weiter mit dem firtz 2.0. Ich habe gestern Abend ein paar Dinge unter der Motorhaube geändert, die vor allem das Haupttemplate und die Extensions betreffen. Test- und spaßeshalber habe ich die 2click-share-Extension von Heise für den f20 portiert. (siehe http://et.enif.uberspace.de).

Im Zuge dessen habe ich ein repo für extensions angelegt: https://github.com/eazyliving/firtz-extensions

Dort werden in Zukunft alle von mir gebauten oder freigegebenen Extensions landen :)

**Comment by eazyliving** [comment]
Ich schließe das hier mal, um etwas eindeutigeres zu öffen.
