### ISSUE TITLE
PWP zeigt Videofenster anstatt Audio-Elemente (seit commit a20f33398274a0a485cc31c483b8fb20d0f1a2f6)

### ISSUE THREAD

**Issue by Reisen-Wandern-Tauchen** [eazyliving/firtz#86]
Hi Christian,

nachdem ich das letzte Update (commit a20f33398274a0a485cc31c483b8fb20d0f1a2f6 "fixed rare bug with missing audioformats in single episodes") eingepflegt hatte, zeigte mir mein Audio-Podcast plötzlich im WebPlayer ein Video-Fenster an.
Verwendete Dateiformate im Player: m4a, mp3, opus (werden auch alle drei als "audio/..." angegeben.
Allerdings wird der Player anstatt in ein audio-Tag in ein appli-Tag geladen.
Ich hab fürs Erste jetzt mal die template/podlove-player.html wieder auf den alten Stand zurückgesetzt. Damit zeigt mir der firtz nun wieder korrekterweise die Audio-Steuerung an.

Irgendeine Idee woran das liegen könnte?

Gruß, Chris

**Comment by eazyliving** [comment]
Oops. Öhm. Ja. Das brauch ich gar nicht nachschauen, was ich falsch gemacht habe. Da fällt mir die faule Zeile sofort ein und was genau daran faul ist.

Du hast aber sicher nur m4a, mp3 und opus? Oder ist da auch noch irgendwas anderes dabei? Etwas, das mit application/ anfängt? :)

**Comment by Reisen-Wandern-Tauchen** [comment]
Es sind auch 3 ebook-Formate (epub, mobi und pdf) dabei - und die definiere ich über eine separate .epi zu jeder Folge dazu.

**Comment by eazyliving** [comment]
Wie ich's erwartet hab, Fehler gefunden. Ich bin halt auch manchmal dämlich. Ich denke, mit dem letzten commit sollt's klappen. Hab's mit einem Feed getestet, der PDF und mpg enthält. Daumen drücken ;)

**Comment by Reisen-Wandern-Tauchen** [comment]
Wow! was für eine Reaktionszeit! :-)
Das klingt doch sehr vielversprechend! Ich werde es am Nachmittag testen und ggf. den Issue schließen oder berichten, sollte es es nicht funktionieren.

**Comment by Reisen-Wandern-Tauchen** [comment]
So! Den letzten Commit getestet und für gut befunden! :-)
Danke!
Funzt alles einwandfrei. Und damit schließe ich diesen Issue.
