### ISSUE TITLE
adnthread

### ISSUE THREAD

**Issue by eazyliving** [eazyliving/firtz#87]
Hallo Leute,

es gibt ja seit Version 1.Irgendwas den adnthread. Damit ist es möglich, Kommentare komplett in ADN laufen zu lassen. Nutzt das jemand? Ich überlege, das aus dem repo rauszuwerfen und dann bei Bedarf eine Extension draus zu machen. 

Bevor ich das aber mache, würde mich interessieren wer das nutzt und der Meinung ist, dass es bitter notwendig ist :)

Danke!

**Comment by Reisen-Wandern-Tauchen** [comment]
Hallo Christian,

also ich nutze das nicht.
Würde für mein Verständnis ja auch voraussetzen, dass alle, die kommentieren wollen einen ADN-Account haben müssten. Und das will ich nicht.

Ich habe aktuell noch das standardmäßige disqus im Einsatz, was aber auch nicht wirklich lebt...
Mir persönlich wäre ein "selbstgehostetes" Kommentarsystem am besten "firtz-eigen" eigentlich am liebsten. Es gibt dazu ja auch einen Ansatz von RonBuehler (https://github.com/RonBuehler/firtz-comment-system). Das habe ich aber leider nicht vernünftig in meiner firtz-Umgebung zum laufen gebracht. (auch wenn ich mich nicht übermäßig lange damit auseinandergesetzt habe) - aber eventuell könnte man das ja als Basis verwenden um ein eigenes Kommentar-System fest im firtz-Repo zu etablieren... (ich würde das begrüßen! vor allem, weil meine Hörer dann keinen Account bei irgendwelchen "Datenkraken" wie google, facebook & co. brauchen...)

**Comment by eazyliving** [comment]
Das Problem mit einem eigenen Kommentarsystem ist, dass an der Stelle dann Code nötig wird, der vor allem auch eine Authentifizierung nötig macht. Weshalb man in Rons Beispiel auch Ordner schützen muss.

Das ist etwas, das ich vermeiden möchte, da ist mir der Sprung Richtung WP zu groß. Ich möchte nicht, dass sich die Nutzer Passwörter merken müssen für Systeme, die ich baue oder verantworte. 

Eine schöne Lösung habe ich natürlich nicht zu bieten, disqus, ADN und twitter (nie gemacht) waren für mich daher die konsequente Linie, das anderen zu überlassen :)

Vielleicht gibt's ja noch andere Ideen? Mal was ganz anderes? Hmmm.

**Comment by Reisen-Wandern-Tauchen** [comment]
Das verstehe ich schon. Ist ein nachvollziehbares Argument. :-)

Die Patent-Lösung dafür habe ich natürlich auch nicht... ;-)
Ohne Datenbank-Backend ist das natürlich nicht so einfach zu realisieren. (aber genau dieses Weglassen von Datenbanken und anderen "aufgeblasenen Systemen" ist ja gerade die große Stärke des firtz...)

Disqus hat zumindest mal den Vorteil, dass man für die Anmeldung auf bestehende Accounts der "Großen" zurück greifen kann.
Aber ein eigenes System (das zu Authentifizierung ev. auf die OpenID-Schnittstellen zurück greift?) wäre mir persönlich halt das Liebste. ;-) (das hat aber definitiv nicht die höchste Priorität - ich denke da gibt es andere Sachen die wichtiger sind)

**Comment by eazyliving** [comment]
Genau so ist's. Priorität hat etwas, das ein wenig aus dem Fokus gerückt ist: Ein anständiger Feed mit möglichst vielen sauberen Metadaten. Die Webseite war ursprünglich gar nicht geplant und der Hack einer halben langweiligen Stunde an einem schummrigen Abend mit etwas zu viel Bier ;-)

**Comment by i42n** [comment]
Ich nutze mittlerweile [ISSO](http://funkenstrahlen.de/blog/2014/10/28/ich-schrei-sonst/) als Kommentarsystem. Benötigt aber eine Backend Komponente, macht also für den Firtz im Allgemeinen keinen Sinn. Aber ich dachte ich lasse das hier mal als Anregung stehen, falls da jemand Spaß am Basteln hat und nichts gegen ein Backend hat.

**Comment by Reisen-Wandern-Tauchen** [comment]
Danke für den Tipp! Das schau ich mir auf alle Fälle genauer an. Das klingt mit SQLite nämlich interessant. Weil es keinen "echten" DB-Server braucht.
Mal schauen, vielleicht fällt da ja ein Add-On für den firtz dabei raus... ;-)))

**Comment by eazyliving** [comment]
Ok... ich werde die ADN-Geschichte aus dem repo nehmen. Das gehört in eine Extension, die ich dann ggf. noch schreiben werde. Sind eigtl. nur ein paar Handgriffe. Ich werde ggf. sogar ein extra repo für AddOns machen.

**Comment by McCouman** [comment]
\0/

**Comment by sthesing** [comment]
Ich nutze es, es ist aber nicht tragisch, wenn es rausfliegt. Freue mich, wenn es als AddOn wiederkommt.
