### ISSUE TITLE
Links gehen nicht.

### ISSUE THREAD

**Issue by Harrysonsan** [eazyliving/firtz#88]
Ahoi!

Ich hab vor viel Zeit einen Firtz aufgesetzt und mich tierisch gefreut, dass ich das hinbekommen hab. Ich bin nämlich extremer Noob in solchen Fragen.
Allerdings gehen da einige Links nicht.

Podcast: http://schmalzstullenministerium.de/sputnik/sputnik/show

Der Link hinter dem Bild links oben lautet aber (ein "/" zuviel):
http://schmalzstullenministerium.de//sputnik/sputnik/show/

Das ist auch das größte Problem. Bei wirklich JEDEM Link ist dieser zusätzliche "/" zuviel. Archiv, ältere Folgen, die Folgen selbst...

Ausnahme ist hier der Feed. Der Link zum mp3-Feed zeigt hier hin:
http://schmalzstullenministerium.de/sputnik/mp3
Er liegt aber hier (ein "sputnik/" fehlt): 
http://schmalzstullenministerium.de/sputnik/sputnik/mp3

Ich würd gern wissen, ob es eine Datei gibt, in der ich die Links einfach reinschreiben kann und so die automatische Linksgenerierung austrickse. Ich bin wie gesagt Programmniernoob, deswegen bin ich vor allem an einer schnellen und einfachen Lösung interessiert.

Edit: Das mit den Slashes gilt auch für die Episodenlinks im Feed. Die Links zu den mp3s funktionieren aber.

**Comment by Reisen-Wandern-Tauchen** [comment]
Hi!

Das klingt mir ganz nach leicht verdrehten Einstellungen in Deiner feed.cfg...
Check darin mal die folgenden Einstellungen:
baseurl:
mediabaseurl:
mediabasepath:

**Comment by Harrysonsan** [comment]
Das kommt beides garnicht in meiner feed.cfg vor... Ich muss dazusagen, dass der Firtz auch schon ziemlich alt ist und dass ich den nicht unbedingt anfassen will, weil auf dem gleichen Server auch noch ein Podlove läuft und ich noch weiß, dass das echt ein Krampf war, beides zu verheiraten. Ich hatte auch schon versucht, mein wordpress auf Multisite zu stellen, woran ich aber gescheitert bin und dann hab ichs gelassen.

Meine feed.cfg:
#: Dies ist Konfigurationsdatei für die allgemeinen Daten des Feeds

title:
SPUTNEWS

description:
Die Nachrichten der Initiative SPUTNIK an der TU Berlin

formats:
mp3

author:
SPUTNIK

summary:
In diesem Podcast informieren wie euch über Dinge, die in der TU Berlin und in der Initiative SPUTNIK so passieren.

image:
http://www.schmalzstullenministerium.de/sputnik/sputnikQUADRAT.png

keywords:
TU Berlin, Hochschulpolitik, SPUTNIK

#: Hier findet Ihr die Kategorien, die Apple bei iTunes eingerichtet hat: http://www.apple.com/itunes/podcasts/specs.html#categories
category:
News & Politics
Education -> Higher Education

email:
henry@schmalzstullenministerium.de

language:
de-DE

explicit:
no

#:kopiert Euch den iTunes-Link einfach aus... *hust* iTunes :D
#:itunes:
#:https://itunes.apple.com/de/podcast/schall-und-rauch/id601805504

#: hast Du einen Account bei disqus? Dann hier den forumshortname (oder wie das heißt) rein.
#:disqus:
#:firtz

#: flattr gibt's natürlich auch. Wirf hier deine FlattrID hin und entferne die Kommentierung!

flattrid:
harrysonsan

**Comment by eazyliving** [comment]
Hiho Henry,

da liegt das Problem: der Bug ist seit Mai 2014 behoben, leider wirst du das mit dem Update machen müssen. Aber warte noch etwas bis zur 2.0. 

Die Audiodateien kannst du mit komplettem Pfad angeben, es sei denn du arbeitest mit auphonic. 

Wie kommt dein firtz zu den Dateien? Auphonic oder epi?

--
Gruß,
Christian Bednarek

**Comment by Harrysonsan** [comment]
Firtz bekommt die per epi. Ich hab unter einsatz von mehreren Flaschen Mate mal ne aktuellere Version raufgespielt und... ES GEHT! IRRE!
Nur im Feed stehen die Dateien mit 0 kb drin. Im Antennapod geht aber alles. ich kann die Dateien streamen und runterladen.

**Comment by McCouman** [comment]
ist doch markdown, also so denke ich?
//link
<pre>&#91;click here](https://example.com/scrambled-eggs.pdf)</pre> Ergebnis => [click here](https://example.com/scrambled-eggs.pdf)
//bilder
<pre>!&#91;Harrysonsan als Bild einfügen](https://avatars0.githubusercontent.com/u/4498456?v=3&s=200)</pre>![Harrysonsan als Bild einfügen](https://avatars0.githubusercontent.com/u/4498456?v=3&s=200)

Grüße M.C.

**Comment by Harrysonsan** [comment]
Danke :)

**Comment by eazyliving** [comment]
Hm. Das mit den 0KB...

Wenn Du manuelle EPIs erzeugst... Du hast in der feed.cfg z.B. stehen:

`formats:
m4a mp3
`
Du erzeugst also einmal m4a und mp3. In der jeweiligen EPI dann steht sowas wie:
`mp3: http://fasel.bla/fasel.mp3 123456`
`m4a: http://fasel.bla/fasel.mp3 789012`
Nur so bekommst Du die Größen per EPI rein.

Ich empfehle allerdings einen auphonic-Workflow, wenn Du auphonic sowieso schon in Gebrauch hast...
