### ISSUE TITLE
" 'English'), " wird in den Episoden angezeigt.

### ISSUE THREAD

**Issue by Harrysonsan** [eazyliving/firtz#89]
Moin!

In meinen Episoden wird als Abschluss immer " 'English'), " angezeigt. Tritt im Firefox und im Chrome auf. Siehe Bild. 

http://schmalzstullenministerium.de/sputnik/sputnik/show

![screenshot](https://cloud.githubusercontent.com/assets/4498456/6187350/ab3d8748-b385-11e4-9c90-1b8e61c00462.png)

Was tun?

VG, Henry

**Comment by Reisen-Wandern-Tauchen** [comment]
Das hat mit dem Flattr-Button zu tun.
Ich habe in meinen Podcasts aktuell das selbe Problem. (allerdings im Bereich der Fußzeile)
Allerdings hatte ich noch keine Zeit mir das näher anzusehen.

**Comment by eazyliving** [comment]
Ja, das ist in der Tat ein Bug seitens flattr. Ich hatte den gemeldet und laut dem Support sollte der behoben sein. Ist er wohl nicht :(

Sobald da einmal drauf geklickt wurde (zB per auto flattr) ist das weg. Das Problem gibt's also nur bei ungeklickten, neuen Buttons. Alternativ kannst Du versuchen, in der feed.cfg den Parameter für die Sprache auszukommentieren, dann wird der Bug dort umgangen.

```
#:language:
#:de_DE
```

so sähe das dann aus.
Ich melde da mal an flattr...

**Comment by eazyliving** [comment]
Scheint, als wäre das behoben seitens flattr.
