### ISSUE TITLE
<3 in den Shownotes bricht Parser

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#90]
Ich hatte heute "**<3**" in den Shownotes. Das hat es aber sowohl auf der Webseite als auch im Feed nicht angezeigt und alles danach auch nicht mehr. Da bricht wohl der Parser. Ist sowas tatsächlich nicht Markdown konform?

**Comment by McCouman** [comment]
jo, es wird ein html tag erwartet. ist leider auch im standard markdown immer wieder ein Fehler. Musste halt Sonderzeichen nehmen: "&amp;lt;" anders gehts och net

**Comment by eazyliving** [comment]
Hach, wie blöde...
Einen Tod wird's da geben müssen. Das Problem ist hier die Funktion strip_tags. Mit der werfe ich HTML aus dem Artikel, der ja eigtl nur Markdown sein sollte...

Die blöde Funktion macht aber genau das, was hier passiert, wenn ein schließendes > fehlt :(

Mal sehen, ob mir dazu irgendwas einfällt. Ich befürchte nicht :(

**Comment by eazyliving** [comment]
Ich habe die Funktion im 2er firtz einstweilen ersetzt. Mal sehen, was ich damit nun kaputt mache... :D
