### ISSUE TITLE
firtz 2.0 - der Weg zum RC

### ISSUE THREAD

**Issue by eazyliving** [eazyliving/firtz#91]
# firtz 2.0

Ihr lieben Freunde des firtz, der erste Releasekandidat des 2.0er firtz kann nicht mehr lange auf sich warten lassen.

Was Ihr im Moment unter http://et.enif.uberspace.de/ findet, ist schon ein guter Start. Ich werde mir über das Wochenende alles noch einmal durch den Kopf gehen lassen, was ich so an Änderungen gemacht habe und ob das alles gut und schön ist.

Der firtz 2.0 hat vor allem diese grundsätzlichen Dinge unter der Motorhaube: 

# 1. quorx

Das neue Standardtemplate ist nun quorx, was jetzt keine große Überraschung ist. Michael wird hoffentlich vor dem Release noch einmal ein Auge auf alles werfen und die Ecken abschleifen :)

#  2. child templates

Das erklärt sich fast von alleine. Zu jedem Template gibt es sekundäre Templates. Im Grunde sind das nur nachgelagerte, aber höher priorisierte Ordner, in denen Dateien schlummern, die Dateien im default-Ordner überschreiben. Es gibt da ein paar Haken und Ösen, aber das erkläre ich zu gegebener Zeit.

# 3. Hooks

Die Child Templates sind Grundvoraussetzung für Hooks. Die sind nämlich nichts anderes als Dateien in bestimmt benannten Ordnern, die zu bestimmten Gelegenheiten beim Rendern hinzugefügt werden. Wer den firtz kennt, der wird sich an die Dateien in /pages oder auch /episode erinnern. Das gibt es nun für ein paar weitere Orte im Renderbaum und auch für die RSS-Feeds.

# 4. Extensions

Die Erweiterungen habe ich ein wenig ausgebaut, was aber im Wesentlichen auch nur eine Nutzung von child templates und hooks ist, nur etwas geordneter. Es gibt nun ein repo für Erweiterungen, Ihr findet es [hier](https://github.com/eazyliving/firtz-extensions).

Das ist nun keine Doku, die wird sicher noch ein wenig auf sich warten lassen. Aber es gibt Euch vll schon eine Übersicht, was denn kommen wird. Ich werde ein paar Nächte über den aktuellen Stand schlafen und die daraus folgenden Änderungen in den RC1 wandern lassen.

Wer jetzt schon Wünsche hat, Fehler findet oder CSS-Quirks lösen möchte: ich bitte drum!

Habt ein gutes Wochenende!

**Comment by eazyliving** [comment]
Ach, ganz vergessen: Es wird keinen Release geben, bevor ich nicht eine Doku dafür am Start habe, die das verdient. Das wird mich mit Sicherheit ein paar Tage kosten, aber vielleicht beginne ich bereits dieses WE damit, denn da habe ich aus familiär/organisatorischen Gründen viel Leerlauf...

**Comment by McCouman** [comment]
bin gespannt :)

**Comment by eazyliving** [comment]
Die Doku nimmt Fahrt auf. Es wird auch einen Text geben, der noch etwas grundsätzlicher als das README erklärt, worum es hier eigentlich geht.

Dennoch, das wird echt unangenehme Arbeit :}

**Comment by eazyliving** [comment]
Und ist immer noch unangenehme Arbeit. Die Doku wird mit Sicherheit nicht 100%ig sauber und vollständig sein. Das bekomme ich sowieso nicht hin. Aber ich sehe im Moment wenig Probleme bei aktuellen Stand, oder?

**Comment by McCouman** [comment]
nö :D
