### ISSUE TITLE
Sonderzeichen in epi-Dateien

### ISSUE THREAD

**Issue by Harrysonsan** [eazyliving/firtz#92]
Moin! :)

Ich hab eben einen Bug gefunden. Und der geht so: Ich hatte eine Episode mit einem "&" im Titel. Nach Upload von mp3 und epi war jedoch der Feed karpott. Als ich das "&" dann durch ein "+" ersetzt hab gings plötzlich wieder. Ich hab das dann noch ein paar mal hin und her vertausch um es zu reproduzieren, was auch funktionierte. Wenn möglich bitte ich um ein Bugfix.

VG, Henry

**Comment by eazyliving** [comment]
Ist der firtz aktuell?

--
Gruß,
Christian Bednarek

**Comment by Harrysonsan** [comment]
Am 14. Januar hab ich mir die damals aktuelle Version raufgezogen. Laut Readme müsste die noch aktuell sein, oder?

**Comment by eazyliving** [comment]
Das Problem ist (leider), dass das framework hinter dem firtz beim erzeugen einer XML-Datei Sonderzeichen nicht für XML, sondern für HMTL erzeugt. Das ist für die Validation leider falsch und macht den Feed kaputt :(

Mit php5.4 und dem aktuellen firtz ist das das in Teilen behoben, aber ich muss jede Stelle einzeln behandeln und demnächst meckern dann die Leute, die noch php5.3 und jünger nutzen. Es ist ein Leid und ich habe ein wenig Hoffnung, das im 2er Firtz im Griff zu haben. Hoffnung :D

**Comment by eazyliving** [comment]
In other words: ich hab da mal was gedreht, aktualisiert den 14er mal bitte. Oder wartet auf den 2er :)
