### ISSUE TITLE
Hi ich bekomme da nen Fehler im neuen RC2

### ISSUE THREAD

**Issue by McCouman** [eazyliving/firtz#93]
Internal Server Error

Fatal error: syntax error, unexpected '['

• src/classes/feed.php:92

**Comment by eazyliving** [comment]
Hi Michael,

ich befürchte, Du gammelst auf einer alten PHP-Version rum, richtg?
Ich änder das mal im Quellcode, ist nicht zwingend nötig, was da läuft :D

**Comment by McCouman** [comment]
Kann sein, ich habe 129 Tickets offen, ich aktualisiere mal. Dachte eigentlich ich hätte die neue schon eingespielt. /*Hust*/

**Comment by McCouman** [comment]
Ich spiele gerade mit PHP Version 5.3.10 auf der Server Instance. Die neue kommt doch erste Oktober 2015 heraus. Oder wie war das?

**Comment by eazyliving** [comment]
Ich weiß nun gerade nicht, welches System Du nutzt, aber die 5.3.10 ist drei Jahre alt.
Ich weiß auch, dass das nichts heißen muss und dass viele Systeme mit LTS (und so weiter und so bla).

Der firtz benötigt, um anständig zu laufen irgendwas >5.4. Ich versuche, das an möglichst vielen Stellen nicht nötig werden zu lassen und mit Versionsabfragen workarounds einzubauen, aber auf Dauer wird das nicht überall klappen.

**Comment by McCouman** [comment]
Nicht so wild ist nur ne Instanz, ich kann jedoch nicht einfach mal eben alles umfrickeln. Da WB ein Cloud System ist. Ich muss die Instanzen erst erzeugen und einspielen damit ich die als "Standard" nutzen kann. Die meisten Instanzen müssen älter sein und werden später von der CIT-Phase nach dem deplyoment in die SIT gebracht. Dort laufen andere Versionen. Jedoch steckt dort ein anderes System dahinter. Zur Zeit komme ich dazu an 129 Baustellen gleichzeitig zu Arbeiten. Das Backend dazu baue ich ja auch gerade neu^^

**Comment by eazyliving** [comment]
Ich glaube, ich habe keine zwei Wörter am Stück verstanden :D
