### ISSUE TITLE
BASEURL nicht https

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#94]
Ich würde gerne meinen firtz auf https umstellen. Dabei hatte ich ein Problem mit der BASEURL:

https://github.com/eazyliving/firtz/blob/master/index.php#L15

Die steht fest auf http. Das bricht so einiges unter anderem den Player unter https, weil der dann nicht via http nachgeladen werden kann.

Kann man nur via Redirect auf https lösen. Allerdings möchte ich das noch nicht aktivieren, da ich nicht sicher bin ob alle Clients mit einem https only Feed klarkommen.

**Comment by i42n** [comment]
Auch nachdem ich in der `index.php` die BASEURL einmal auf https umgebogen habe, liefert der Server immer noch sowas hier aus `<link href="http://podcast.funkenstrahlen.de/src/pwp/static/podlove-web-player.css" rel="stylesheet" media="screen" type="text/css" />`

Ich verstehe gerade nicht wieso...

**Comment by eazyliving** [comment]
Liegt am firtz. Hardcoded http://. Schlag mich ;)

**Comment by eazyliving** [comment]
Was ich damit sagen wollte: werde ich (aber erst morgen) für den alten und neuen fixen. Schaff's heute nicht mehr.

**Comment by eazyliving** [comment]
Korrigiere: hab's jetzt schon gefixt. Wenn Du magst, teste es mal kurz durch.

**Comment by McCouman** [comment]
und war doch garnicht so schwer :P - geht bei mir auf dem BananaPI super :)

**Comment by i42n** [comment]
Mit so viel Engagement kann ich gar nicht mithalten! Mach dir nur mal nicht so viel Stress, das hat doch alles seine Zeit.

Ich wollte das eben mal testen, aber du hast das auf den master commited und nicht auf den quorx 2.0 branch. Hat das einen Grund?

**Comment by i42n** [comment]
Oh, ist ja auch auf dem quorx branch. Nicht gesehen...

**Comment by i42n** [comment]
Funktioniert.
