### ISSUE TITLE
site.html mehr modularisieren

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#95]
Ich würde gerne die Sidebar durch ein Child Template ersetzen. Da aber alles noch in `site.html` drinhängt ist das gar nicht möglich ohne sehr viel doppelten Code.

Daher mein Wunsch: `site.html` in mehrere Files splitten.

**Comment by eazyliving** [comment]
Muss ich drüber meditieren. Nicht, weil es nicht ginge. Eher, weil dann das gesamte Template entsprechend aufgebaut sein müsste. Was dann wiederum... naja, ich meditiere mal :)

**Comment by McCouman** [comment]
Ich mache da mit! Das ist recht einfach und baue ich nächsten Wochen noch um. 
Da macht so einiges kein Sinn, alles in eine Seite zu hauen.
Gehen Tut das auf jeden Falle recht simpel und hatte bis vor kurzen ca 20 Templates, sprich jede Seite eine andere Sidebar.

Jedoch kann das ja jeder selber basteln, weshalb der Standard Ansatz nicht zu hoch und unübersichtlich sein sollte, da bastle ich auch noch am Ansatz herum.

Das Design geht auch langsam voran ;) Hier gibet dann die Vorschau: http://firtz.wikibyte.org

**Comment by i42n** [comment]
Das Design gefällt mir schon echt gut! Wird das dann hier rein gemerged?

**Comment by McCouman** [comment]
liegt an Christian und daran, wie ich mich entscheide, das Design weiter auszubauen. Sprich: ist das alles ok, oder überfordert das am Ende den Nutzer. 

Ich habe dutzende Ideen, jedoch kann man nicht alles umsetzen. Da es sonst am Ende nicht mehr so Firtzig einfach ist. Und darauf kommt es ja an.

Ich werde aber die Ideen in andere Designs umsetzen und die sind ja, Dank! des rc2.0 nun auch als weiteres Theme einfach einzusetzen. 

Habe noch 3 weiter in der Mache. 
QuorX 2.0 - geplant so Anfang Mai.
QuorX Pinty (mit Bildern/Episode - kommt Ende so gegen Juni heraus jedoch kostet dann was), 
FliX3 Lima (neues Podbe4 Design / light Version - kommt Ende Mai) und 
DOMtree Landing mit dem Menü rechtsbündig, kommst für ein paar Euro dann gegen Mitte Juli.

Wie dann supporten weis ich auch noch nicht. Ich baue noch eine Seite für "Firtz-Designs" wo ich alle 12 Designs als Demo vorstelle und man Sie auch bekommt. Vielleicht mache ich auch ein paar Videos :P

**Comment by eazyliving** [comment]
Es ist ja nun so: Wie weit treibe ich die Modularisierung.
Möchte ich am Ende wie WP aussehen in den templates? Für jeden noch irgendwie geometrisch getrennte Fläche eine eigene Datei?

Oder modularisiere ich nach Gutdünken? Der Punkt ist, gerade bei der Seitenleiste folgender: Wenn ich die weglasse (weil dann ggf. sidebar.html leer ist im Child), zerstört das den Aufbau der Seite?

Ich könnte durchaus mit einer Trennung nach:

Kopf
Mitte
Seite
Fuß

leben. Aber in wiefern könnte das den Aufbau der Seite stören, wenn etwas fehlt? Horizontal sehe ich da wenig Probleme. Ohne foot.html gibt es eben keinen Fuß. Aber gerade die Seitenleiste müsste das dann im CSS aushalten, nicht aufzutauchen. Wenn aber der Content-Teil pixelgenau darauf ausgelegt ist, eine z.B. 150px breite Seitenleiste zu haben...

Ihr wisst, was ich meine :)

**Comment by eazyliving** [comment]
Und bevor ich es vergesse: Es ist dann ja doch wie bei WP. Wer es anders haben will, kann sich das natürlich so zimmern. Es geht hier ja nur um das Standardtheme :)

**Comment by McCouman** [comment]
JO! denke ich auch. Daher können wir auf jedenfalle weitere Themes nachlegen, die dann so auseinander gebastelt sind. Das Standard im Firtz, sollte denke ich auch "einen" Einheitsbrei haben. Wer das ändern will, kann dann die "auseinander gedröselte" Variante von mir haben. Ich frickele an beiden herum.

Hier mal meine site.html

<pre>&lt;check if="{{!@showpage}}">
	<true>
			
		<check if="{{@singlepage==false}}">
			
			
			<include href="{{'templates/header.html'}}"/>
			
				
			<include href="{{'templates/navigation.html'}}"/>

			
			<include href="{{'templates/page-home.html'}}"/>
			
			
			<include href="{{'templates/footer.html'}}"/>
			
		</check>
			
		
		
		<check if="{{@singlepage}}">
		
			
			<include href="{{'templates/header.html'}}"/>
			
				
			<include href="{{'templates/navigation.html'}}"/>

					
			<include href="{{'templates/blog_start.html'}}"/>
		
			<repeat group="@items" value="{{@item}}">
				<include href="{{'templates/page-blog.html'}}"/>
			</repeat>

				
			<include href="{{'templates/blog_end.html'}}"/>
			
		</check>
		
	</true>
			
	<false>
		<include href="{{@showpage}}"/>
	</false>
</check>
</pre>

Wie man im Bereich "blog" jedoch sehen kann, ist es Design technisch, wie Christian schon angesprochen hat, nicht ganz einfach. Ich bin da noch auf der Suche nach einer "guten" Lösung.

**Comment by eazyliving** [comment]
Ich lass das hier mal ganz offen. Eigentlich eine spannende Diskussion, die dahinter steckt. Ein Glas Rotwein und ein paar gute Gespräche wären hier angebracht. Nebenan hat ein Winzercafé eröffnet. Wir sollten uns mal einen Abend dort reinsetzen ;)

**Comment by McCouman** [comment]
Ich wollte nun nicht gleich ein neues Issue aufmachen.

Jedoch habe ich nun  das CSS fast neu erarbeitet und habe nun auch die Animation eingebaut.
Die Frage ist halt, ob das ganze nicht auch, wie die Farben gegen zu checken ist oder ob es als Standard mit hinein gehen soll. Vielleicht mag der ein oder andere es nicht und will es abstellen.

![bildschirmfoto 2015-04-04 um 15 04 17](https://cloud.githubusercontent.com/assets/3239082/6992738/75939050-dadc-11e4-892c-72f26d877763.png)

**Comment by eazyliving** [comment]
Es spricht wenig dagegen, einem template haufenweise Variablen mitzugeben. Eine davon könnte das Ein-/Ausschalten der Animationen sein.

Wie das geht? Steht noch nicht in der Doku aber ich erkläre es kurz:

Im template-Ordner kann eine template.cfg stecken. Hier stehen die defaults aller Template-Variablen:
```
color #fff
animation off
```
Diese kann man auf zwei Wegen überschreiben. Entweder in der feed.cfg unter templatevars:

```
templatevars:
color #ddd
animation on
```
und zu guter Letzt auch noch, aber das sollte man eigtl nicht machen im html des template selbst:
```
<!-- {{@templatevars.color = '#ccc' }} -->
<!-- {{@templatevars.animation = 'off' }} -->

In der template.cfg kannst Du also die defaults mitgeben die greifen, wenn der Nutzer des templates nichts daran ändern möchte :)

Toll, wa? :D

**Comment by eazyliving** [comment]
Achso... weshalb rede ich hier von Variablen und nicht von Attributen? Naja, eigentlich habe ich anfangs nicht drüber nachgedacht, sondern es einfach so genannt. Aber letztlich sind diese Attribute variabel. Es spricht nichts dagegen, diese Werte innerhalb der Darstellung zu ändern.

Gäbe es z.B. einen Wert für den Hintergrund des DIVs der Episode, ließe der sich über ein paar kurze Befehle sogar im Template wechseln, sodass die erste Episode blau, die nächste grün, dann wieder blau... You get it? :)

**Comment by McCouman** [comment]
äh... letzeres ist noch cool aber gerade nicht meine Idee.

Was genau, kann ich denn machen um zu überprüfen?
<code>animation off</code>
=> gibt <code>off</code> aus. 

Das bringt mir jetzt nicht viel.
Der Code muss wenn on angegeben ist heraus fallen im Theme:
<code>data-firtz-scrollspy="{cls:'firtz-animation-slide-top'} ... noch mehr zustände ..."</code>

Wie kann ich denn das gegenprüfen?
if und so.

<code><check if="{{@templatevars.animation == on }}">data-firtz-scrollspy="{cls:'firtz-animation-slide-top'}"</check></code>

geht net... /*hust*/

**Comment by McCouman** [comment]
ok zugegeben ich bin ein absoluter Blödföhn...

<code>&lt;check if="{{@templatevars.animation == 'on'}} "></code>

**Comment by eazyliving** [comment]
:)

**Comment by i42n** [comment]
@McCouman Deine `site.html` ist genau das wovon ich träume! Warum entwickelst du das denn komplett parallel, statt ab und zu mit dem Hauptprojekt hier zu mergen?

**Comment by McCouman** [comment]
Ich habe 12 Testsysteme und versuche das QuorX hier und da zu modifizieren oder bastel für Kunden. 
Es ist mir schlicht nicht möglich alles zusammen zu bringen und dazu habe ich auch nicht die Zeit.
Aus Gründen baue ich da auch Dinge rein und baue sie nachher wieder aus (für Tests).

**QuorX II soll jedoch schlank und übersichtlich bleiben. Das ist der Wunsch von Christian und den habe ich zu respektieren.**

*Wenn wir uns aus Gründen der Übersichtlichkeit und Handharbung dann in der 2.1 dafür entscheiden, das doch anders zu machen. Weil alles so funktioniert wie erwünscht, dann können wir das immer noch modularer aufbauen.*

Mir ists auch modularer lieber. Jedoch gerade jetzt wo wir Plugins und mehr Möglichkeiten haben, ist es schwierig, das einfach so rein zu hauen. Dann sieht es wie bei Christians Vorschau-Firtz aus / * Hust * /. Und das geht meines erachtens mal gar nicht. Weil => sieht beschissen aus.

**Was ich jetzt also versuche ist:**
- erst einmal die Buttons und Kommentarfunktion und die gesamten Dinge, so rein zu bauen und gleichzeitig zu sortieren, das es am Ende des Tages auch wie ein Blog aussieht. 
- Code zu verschlanken
- Kommentare sollen mehr Verständnis zum Aufbau und Design geben.
- Suche ist scheiße mit dem JS und funktioniert nicht so wirklich. Da muss unbedingt was funktionales her (Extension).
- Es soll auf allen Geräten erst einmal so einigermaßen funktionieren (Responsive Design).
- Automationen sollen da rein und ein/ausschaltbar sein.
- Die Hooks müssen an die richtig Stelle + loops für die allgemeinen Erweiterungen. 

Aus den vielen Möglichkeiten die man nun hat muss ich also "eigentlich" alle Möglichkeiten einmal aufbauen, da Sie sonst Designfehler verursachen und damit auch Seiteneffekte erstellen.
Das finde ich gerade sehr viel Anspruchsvoller als das Design am Ende auseinander zu frickeln, um es am zum Schluss wieder zusammen zu stöpseln.

Meine Arbeit ist zu dem kostenlos und jedes mal ein check in / out zu machen - da komme ich nicht voran. So viel Zeit habe ich nicht und kann ich auch nicht dafür aufbringen.

**Comment by i42n** [comment]
> Meine Arbeit ist zu dem kostenlos und jedes mal ein check in / out zu machen - da komme ich nicht voran. So viel Zeit habe ich nicht und kann ich auch nicht dafür aufbringen.

Ich würde auch gerne ein wenig mitarbeiten und eventuell Pullrequests stellen. Ich möchte aber vermeiden mir Arbeit zu machen, die du schon längst gemacht hast. Leider kann ich aktuell nicht absehen, was dein Stand ist (Nur das Ergebnis auf einer Testseite zu sehen, reicht da nicht). Das hält mich gerade ein wenig davon ab da Zeit reinzustecken. Ich verstehe aber natürlich auch, dass es deutlich aufwendiger für dich ist, das ständig zu mergen.

Ist es denn vorgesehen, dass du deinen Stand hier ins Projekt einbringst, sobald das "fertig" ist?

Die Ziele die du dir gesetzt hast, finde ich super! Genau der richtige Weg. Danke für deine Arbeit :)

**Comment by McCouman** [comment]
Ja, ich weis das Du gerne mithelfen willst. Jedoch müsste ich dann deine Arbeit auch noch gegen checken und auf vielleicht defects im design nachgugen^^

So lange ich keine "erste" Version habe, die auch mir für den Anfang gefällt, wird es da nix geben.
Danach freue ich mich auf Ideen :)

Und ja, der QuorX kommt direkt hier rein, jedoch nicht durch mich! 

Es gibt eine Download Schnittstellen mit API und so, dort kann das **release** von Christian geladen werden. Er schaut sich das dann an um Fehler oder Zeugs (was ich vielleicht falsch oder versehentlich gelöscht habe) rein zu bauen was den standard Firtz-Aufbau 2.0 betrifft. Christian macht ein eigenen Meilenstein und haut es in die Versionen hier ;) 

=> Damit landet also am Ende alles hier, nur richtig zusammen gesetzt (man hoffts :) )

Der Ablauf ist eigentlich einfach:
1.) CID - hier frickel ich an allem ein wenig herum...
2.) #Bugs die von mir kommen und anderen aus den issues hier laufen da ein.
3.) #fixing CID der #Dugs & defects
4.) SID - deployment in das testsystem + vielleicht wieder Bugfixing (meist nur CSS zeugs/kleinigkeiten der Skallierung)
5.) SID => Release. Hier kann Christian das 1.0.0 Downloaden
http://firtz-designs.wikibyte.org/downloads/?firtz-design=rc1-quorx2_1.0.1&p=release
6.) Christian macht Voodoo und je nach stand kommt es in den Firtz.
7.) Den Stand schaue ich mir dann noch einmal an und baue die dinge ein, die schon für die 2.1 sein sollen. / Die wurden schon getestet jedoch noch nicht weiter entwickelt. (keine Zeit oder out of scope)
8.) ist das alles drin und sicher verwahrt mit Dokumentation, dann gibt es ein Pilot
http://firtz-designs.wikibyte.org/downloads/?firtz-design=rc1-quorx2_1.1.1&p=pilot
9.) wir entscheiden dann was wir aus dem Pilot mit hinein nehmen und was die Bugfixes sind. Dann gibt es ein QuorX II :)
10.) Am Ende gibts einfach ein free download bei mir (reines Template!) + hier der Meilenstein mit dem QuorX II unter der Haube:
http://firtz-designs.wikibyte.org/downloads/?firtz-design=rc1-quorx2_2.0&p=public

Du findest (noch nicht alles eingetragen!) meinen Kopf und Denkansätze für den Public QuorX auch unter Trello:
https://trello.com/b/SXxvOPHA/quorx-2-0

**Comment by eazyliving** [comment]
Ja, aber der @McCouman rückt die PIN nicht raus ;)

**Comment by McCouman** [comment]
Sorry ich hatte am WE leider kaum Zeit und meine Server musst gebackupt werden. Es was Backup Sonntag. ^^ Da konnte ich nix deployen was man hätte nunderladen können - diesen Sa. sicher :P

**Comment by eazyliving** [comment]
Und da ist's dann auch. Im Moment habe ich den qourx rc1 im child-template q2. Bitte beachtet: Seiten (unter pages) werden leider doppelt angezeigt, weil ich noch keine gute Idee hatte, wie die template-Engine bei einem glob doppelte rausholen kann. Könnte schmutzig werden ;)

**Comment by McCouman** [comment]
hatte ich auch schon gestern bemerkt^^ ist aber vom Rundgedanken her eigentlich auch richtig. habe daher einfach die pages gelöscht - dann funzt das :)

**Comment by eazyliving** [comment]
Ich hab das Problem mit den doppelten Pages - etwas krude - gelöst. Nicht schön, aber funktioniert :)
