### ISSUE TITLE
Template Extensions funktionieren nicht

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#96]
Ich habe soeben auf die akt. Version des firtz upgedated und möchte nun Extensions nutzen. Ich habe dazu aus dem Extensions Repo unter anderem die shariff Extension bei mir reinkopiert.

Leider wird aber nichts in den Content der Seite eingebaut. Habe an der Extension so wie sie im Repo liegt nichts geändert.

**Comment by eazyliving** [comment]
Die extensions, jedenfalls die meisten, funktionieren erst mit dem neuen firtz. Du hast den?

--
Gruß,
Christian Bednarek

**Comment by i42n** [comment]
Ich habe auf dem aktuellsten branch `quorx` aufgesetzt. Das ist der neuste.

**Comment by eazyliving** [comment]
Ok, seltsam. Habe eben unter http://quorx.firtz.org/demo/show einen komplett frischen firtz mit shariff aufgesetzt. Klappt.

**Comment by i42n** [comment]
Ich nutze auf jeden Fall den aktuellen Code. Kann ich das irgendwie mehr debuggen, denn ich kann gut nachvollziehen, dass das so schwer für dich ist rauszufinden was da bei mir falsch läuft.

**Comment by i42n** [comment]
Tatsächlich funktioniert auch die atom Extension nicht. Unter https://podcast.funkenstrahlen.de/fs/atom/mp3 ist nichts erreichbar. Das macht das Bild zumindest ein bisschen klarer.

Leider weiß ich nicht wie ich das debuggen kann...

**Comment by eazyliving** [comment]
Fangen wir unten an. Die extensions liegen in ext/ ?

--
Gruß,
Christian Bednarek

**Comment by i42n** [comment]
Ich habe hier mal meinen aktuellen Stand hochgeladen. So liegt das aktuell auf dem Server.

https://github.com/i42n/firtz/tree/funkenstrahlen

**Comment by eazyliving** [comment]
Sorry, ich war ein paar Tage überarbeitet :) Ich schau's mir jetzt an.

**Comment by eazyliving** [comment]
So. Ich hab deinen Branch mal unter quorx.firtz.org installiert. https musste ich mangels https für firtz.org rauswerfen. Klappt aber alles.

Könnte dann natürlich wieder mit dem https zu tun haben,...

**Comment by i42n** [comment]
Das ist natürlich eine interessante Entwicklung. Jetzt bin ich fast noch ein bisschen ratloser also zuvor.

Ich kann mir nicht vorstellen, dass das an https liegt. Vielleicht ein Problem mit der PHP Version? Ich habe das auf Uberspace am Laufen.

PS: Kannst du das von der Testdomain wieder runternehmen die Tage? Sonst wird Google verwirrt ;)

**Comment by i42n** [comment]
Habe eben nochmal bei Uberspace mein komplettes Web Verzeichnis gelöscht und von Github neu geladen, nur um sicher zu gehen, dass ich den gleichen Stand nutze.

**Comment by McCouman** [comment]
PHP Versionen in meinen Test, gleich am Anfang des RC 1.0
mit 5.3 => Fehlerausgabe
mit 5.4 => ging es glaube ? äh öh - vergessen...
mit 5.5 => geht
mit 7.0 => geht

**Comment by eazyliving** [comment]
Ja, 5.3 wird wohl über die Wupper gehen mit dem 2er firtz. Gerade wg. der Extensions. 5.4 ist Minimum. Aber das sollte Stefans Problem nicht sein. Bei den ubernauten sollte 5.4 Standard sein, oder?

**Comment by i42n** [comment]
Mein uberspace sagt:

```
[i42n@auriga ~]$ cat ~/etc/phpversion
## 2013-03-12 /usr/local/sbin/uberspace-account-create.sh
PHPVERSION=5.4.11
```

**Comment by i42n** [comment]
Habe mal auf 5.6.6 umgestellt. Ändert nichts. Also liegt es nicht an php...

**Comment by eazyliving** [comment]
Ich werd mir heute Abend einen uberspace klicken und das durchspielen. 

--
Gruß,
Christian Bednarek

**Comment by i42n** [comment]
Mach dir bloß nicht zu viel Arbeit damit, wir haben Feiertage :)

**Comment by i42n** [comment]
Eben getestet: Komplett frische Seite mit dem firtz Repo unter [i42n.auriga.uberspace.de/firtz](i42n.auriga.uberspace.de/firtz) aufgesetzt. `.htaccess` angepasst, da sonst Subfolder nicht gehen. Extensions installiert. Geht.

Unter [i42n.auriga.uberspace.de/fs](i42n.auriga.uberspace.de/fs) mein Repo installiert und Extensions installiert. Geht.

Unter [podcast.funkenstrahlen.de](podcast.funkenstrahlen.de) genau das selbe gemacht. Extensions gehen nicht.

Fazit: Liegt nicht an PHP auf uberspace. Liegt nicht an meinem Code. Liegt nicht an deinem Code.

Seltsam.

**Comment by i42n** [comment]
Einziger Diff zwischen den beiden Ordnern:

```
[i42n@auriga web]$ diff podcast.funkenstrahlen.de/ html/fs
Common subdirectories: podcast.funkenstrahlen.de/doc and html/fs/doc
Common subdirectories: podcast.funkenstrahlen.de/ext and html/fs/ext
Common subdirectories: podcast.funkenstrahlen.de/feedimages and html/fs/feedimages
Common subdirectories: podcast.funkenstrahlen.de/feeds and html/fs/feeds
Common subdirectories: podcast.funkenstrahlen.de/.git and html/fs/.git
diff podcast.funkenstrahlen.de/.htaccess html/fs/.htaccess
11,13c11,13
< RewriteCond %{HTTPS} !=on
< RewriteCond %{ENV:HTTPS} !=on
< RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R=307,L]
---
> #RewriteCond %{HTTPS} !=on
> #RewriteCond %{ENV:HTTPS} !=on
> #RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R=307,L]
20c20
< RewriteRule .* index.php [L,QSA]
---
> RewriteRule .* fs/index.php [L,QSA]
Common subdirectories: podcast.funkenstrahlen.de/images and html/fs/images
Common subdirectories: podcast.funkenstrahlen.de/LOCAL and html/fs/LOCAL
Common subdirectories: podcast.funkenstrahlen.de/media and html/fs/media
Common subdirectories: podcast.funkenstrahlen.de/src and html/fs/src
Common subdirectories: podcast.funkenstrahlen.de/templates and html/fs/templates
Common subdirectories: podcast.funkenstrahlen.de/tmp and html/fs/tmp
```

**Comment by McCouman** [comment]
ähm nur mal so als Gegenfrage. Also so nen PHP kommt meist selten allein...

Was ich damit sagen will => php-cgi, php-fm, php-DenkDuWeistWasIchMeine.
Vielleicht gibt es da ein Problem und hatte deshalb mein PHP noch einmal neu installiert. Generell gibt es ein Problem, wenn Du 5.3 auf 5.4 updatest. Da die 5.3 nur die "Neuerungen" mit bekommt, jedoch noch über fm läuft. Das ist jedoch veraltet und gibt es nicht mehr unter der 5.4 und 5.5 hat die komplette Abkapslung. Sprich 5.5 ist nicht einfach updatebar auf die 5.4. Wenn das doch geht ist es eine 5.3 zu 5.4 Upgrade. 

Im fehlen also die wichtigen Dinge wie der richtige Umgang mit den Namespaces. Sie werden daher nur "modelliert" jedoch nicht richtig verwendet.

**Comment by eazyliving** [comment]
Ich hab kein Wort verstanden. Ehrlich :)

**Comment by i42n** [comment]
@McCouman Ich verstehe auch nicht genau was du meinst. Was ich meine zu verstehen ist, dass ein Update der PHP mit Schwierigkeiten verbunden sein könnte, die ich nicht bedacht habe. Ich manage aber die PHP Installation gar nicht selbst. Das wird von Uberspace bereitgestellt. Ich habe nur in der Config eingetragen, welche PHP Version von Uberspace genutzt werden soll.

Ich halte es außerdem mittlerweile für ausgeschlossen, dass es ein PHP Versionsproblem ist. Schließlich macht es nur unter der eigenen Subdomain Probleme. Siehe oben.

**Comment by i42n** [comment]
Nur zur Vollständigkeit hier die Antwort von Uberspace zum Problem:

> Auch nicht so wirklich. Also, wir realisieren das mit den Pseudo Subdomains folgendermaßen, du hast in deiner vhost Config den folgenden Eintrag:

```
# If there is a host-specific pseudo-DocumentRoot, use it instead of the default one
RewriteCond %{REQUEST_URI} !^/f?cgi-bin/
RewriteCond /var/www/virtual/i42n/%{HTTP_HOST} -d
RewriteRule (.*) /var/www/virtual/i42n/%{HTTP_HOST}/$1
```

> ... und damit tricksen wir das mit den Subdomains. Nach deiner Beschreibung beißt sich das vermutlich irgendwo mit Firtz, wo und wie genau kann ich dir aber auch nicht sagen. Viele Wege führen nach Rom, du kannst das auch in deinen html-Folder legen und die offizielle Doku von Firtz befolgen, _falls_ die da eine best practice haben.

**Comment by i42n** [comment]
Mir ist aber auch nicht so richtig klar, warum genau Extensions brechen durch eine Rewrite Rule. Dafür kenne ich den Firtz nicht genau genug. Wird da irgendwie mit Pfaden gespielt, die dadurch brechen könnten?

**Comment by eazyliving** [comment]
Ist die einzige Erklärung die mir da einfällt. 

--
Gruß,
Christian Bednarek

**Comment by i42n** [comment]
Hm. Da bleibt mir eigentlich nur übrig alle meine Extensions direkt in den Code per Hand reinzufrickeln. Habe deshalb aktuell auch keine Kommentare.

**Comment by eazyliving** [comment]
Um Himmels Willen nein. Du machst jetzt mal nix und wartest mal bis heute Abend. Ich hab da ne Idee. 

--
Gruß,
Christian Bednarek

**Comment by eazyliving** [comment]
Aktualisiere mal bitte und gib kurz bescheid, wenn das passiert ist. Danke :)

**Comment by i42n** [comment]
done.

**Comment by eazyliving** [comment]
Sollen wir das Spiel vll auf Skype weiterspielen? :) (christian.bednarek)

**Comment by i42n** [comment]
Mit deinem Debug herausgefunden, dass BASEPATH auf `/home/i42n/web/html` zeigt. Da liegt natürlich mein Code nicht, sondern ich habe den in `/var/www/virtual/i42n`. Vielleicht habe ich da aber auch was falsch aufgesetzt im Uberspace?

**Comment by i42n** [comment]
Ich schaue mir das später nochmal genauer an.

**Comment by eazyliving** [comment]
Hmhmhm... BASEPATH ist $_SERVER['DOCUMENT_ROOT']. Darauf hast Du keinen Einfluss, das steckt ja in der Config des Apaches...

**Comment by eazyliving** [comment]
Wirf doch mal bitte das hier in eine test.php und zeig mir das Ergebnis:

```
<pre>
<?php print_r($_SERVER);?>
</pre>
```

**Comment by i42n** [comment]
```
Array ( [PHPRC] => /home/i42n/etc [USER] => i42n [PATH] => /command:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin [PWD] => /var/www/virtual/i42n/fcgi-bin [HOME] => /home/i42n [SHLVL] => 0 [ORIG_SCRIPT_NAME] => /fcgi-bin/php-fcgi-starter [ORIG_PATH_TRANSLATED] => /var/www/virtual/i42n/podcast.funkenstrahlen.de/index.php [ORIG_PATH_INFO] => /index.php [ORIG_SCRIPT_FILENAME] => /var/www/virtual/i42n/fcgi-bin/php-fcgi-starter [SCRIPT_NAME] => /index.php [REQUEST_URI] => /fs/debug [QUERY_STRING] => [REQUEST_METHOD] => GET [SERVER_PROTOCOL] => HTTP/1.1 [GATEWAY_INTERFACE] => CGI/1.1 [REDIRECT_URL] => /index.php [REMOTE_PORT] => 39386 [SCRIPT_FILENAME] => /var/www/virtual/i42n/podcast.funkenstrahlen.de/index.php [SERVER_ADMIN] => hallo@uberspace.de [DOCUMENT_ROOT] => /var/www/virtual/i42n/html [REMOTE_ADDR] => 141.70.81.135 [SERVER_PORT] => 443 [SERVER_ADDR] => 95.143.172.187 [SERVER_NAME] => podcast.funkenstrahlen.de [SERVER_SOFTWARE] => Apache/2.2.15 (CentOS) [SERVER_SIGNATURE] =>
Apache/2.2.15 (CentOS) Server at podcast.funkenstrahlen.de Port 443
[HTTP_X_FORWARDED_FOR] => 141.70.81.135 [HTTP_X_SSL_CIPHER] => DHE-RSA-AES256-SHA SSLv3 Kx=DH Au=RSA Enc=AES(256) Mac=SHA1 [HTTP_X_FORWARDED_PORT] => 443 [HTTP_X_FORWARDED_HTTPS] => on [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.8,de;q=0.6 [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36 [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 [HTTP_CACHE_CONTROL] => no-cache [HTTP_PRAGMA] => no-cache [HTTP_CONNECTION] => close [HTTP_HOST] => podcast.funkenstrahlen.de [HTTP_AUTHORIZATION] => [HTTPS] => on [SCRIPT_URI] => https://podcast.funkenstrahlen.de/fs/debug [SCRIPT_URL] => /fs/debug [REDIRECT_STATUS] => 200 [REDIRECT_HANDLER] => php-fcgid [REDIRECT_HTTP_AUTHORIZATION] => [REDIRECT_HTTPS] => on [REDIRECT_SCRIPT_URI] => https://podcast.funkenstrahlen.de/fs/debug [REDIRECT_SCRIPT_URL] => /fs/debug [REDIRECT_REDIRECT_STATUS] => 200 [REDIRECT_REDIRECT_HTTP_AUTHORIZATION] => [REDIRECT_REDIRECT_SCRIPT_URI] => https://podcast.funkenstrahlen.de/fs/debug [REDIRECT_REDIRECT_SCRIPT_URL] => /fs/debug [REDIRECT_REDIRECT_HTTPS] => on [FCGI_ROLE] => RESPONDER [PHP_SELF] => /index.php [REQUEST_TIME_FLOAT] => 1429129327.5401 [REQUEST_TIME] => 1429129327 )
1
```

**Comment by i42n** [comment]
Ich denke mir ist das Problem klar geworden.

BASEPATH zeigt auf `/var/www/virtual/i42n/html/`. Dorthin habe ich nun auch meinen Code geschoben, allerdings liegt der da in einem Unterordner `podcast.funkenstrahlen.de`. Wenn du also einfach `/ext` and den BASEPATH hängst, passt das nicht. Mir ist aber auch nicht ganz klar, warum BASEPATH bzw. `$_SERVER['DOCUMENT_ROOT]` nicht das `podcast.funkenstrahlen.de` mit drin hat.

**Comment by i42n** [comment]
Habe bei Uberspace nachgefragt. DOCUMENT_ROOT lässt sich nicht ändern.

Ich sehe also 2 Möglichkeiten: 
1. Ich passe den PATH bei mir manuell an, so dass es zum Uberspace passt. Das wäre dann aber eine spezielle Lösung für mich, da das nicht auf jeden Firtz User passt.
2. Es gibt eine andere Möglichkeit mit Pfaden unter PHP zu arbeiten, die nicht auf Apache beruht, sondern die Verzeichnisstruktur direkt auf dem Server nutzt?

**Comment by i42n** [comment]
Könnte man die Extensions nicht mit einem relativen Pfad laden, wie das auch für die `feed.cfg` passiert? 

Also einfach ein `$main->set('EXTENSIONDIR','./ext');` setzen und dann beim Laden nutzen? So bräuchte man nicht die DOCUMENT_ROOT.

**Comment by eazyliving** [comment]
Genau so werden wir's machen :) Sobald ich Zeit habe (noch heute!) ändere ich das. Und dort, wo es nötig wird.

**Comment by i42n** [comment]
Wunderbar :)

Ich denke hier:
https://github.com/eazyliving/firtz/blob/quorx/src/classes/firtz.php#L125
und hier:
https://github.com/eazyliving/firtz/blob/quorx/index.php#L10

Dann klappts hoffentlich ;)

**Comment by eazyliving** [comment]
So isses. Und unter et.enif.uberspace.de läufts schon.

**Comment by eazyliving** [comment]
So. Probiers mal aus, wenn Du Zeit hast.

**Comment by i42n** [comment]
Funktioniert. Wunderbar :)

**Comment by i42n** [comment]
Fliegt die debug Funktion dann wieder raus? Denke schon, dass das wieder weg sollte.

**Comment by eazyliving** [comment]
Japp!
