### ISSUE TITLE
Suche mit Enter starten

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#98]
Das Tag-Suchfeld kann aktuell nur mit einem Mausklick auf "Suchen" bedient werden. Wäre cool, wenn das auch via Enter-Taste gehen würde.

**Comment by McCouman** [comment]
Ist auch ein Issue denn ich gerne gefixt sehen würde. Ich habe da aber schon eine Lösung gebaut gehabt. Jedoch ist das nach meinen Server Abstürzen mit in die ewigen ....

Naja ich mache das neu hust. Ist ja ganz einfach. Nur müsste ich die Überprüfung in die Extension mit reinbauen. Ob da Christian so begeistert ist weis ich nicht. Geht aber ganz einfach.   

Das JS-Code etwa, ist nur weil Firtz keine Parameter als $_GET übergeben werden, also "?s=Suchanfrage" gibt es nicht.

Mal vom JS-Code abgesehen (der mir nicht ganz schlüssig ist aber funzt) - Ist das schon ne sehr gut Idee für Tablets + Phones, wo ein Enter nicht immer richtig modular geht (etwaigen der trip:links) da nicht jede Tastatur auch ein direktes Enter als Ausführen in einem input übergeben wird (Android 4.2/4.3 und Android Tablet 7" wo es sogar in der Docu erklärt wird. Dort gibt es z.B auch kein border-radius).

**Comment by eazyliving** [comment]
Öhm. Das soll eigtl auch so sein. Irgendwo steckt da ein if (e.keyCode==13) das das übernehmen sollte. Weshalb das gerade nicht mag, weiß ich auch nicht :(

**Comment by McCouman** [comment]
e.keyCode==13 ? Das ist eine Funktion um eine Windoof Tastatur zu bedienen. Geht so weit ich weis aber nur, wenn Du Firefox nutzt? Mir ist das unter Mac/Linux nicht bekannt...

**Comment by eazyliving** [comment]
m(

--
Gruß,
Christian Bednarek

**Comment by McCouman** [comment]
Habe das jetzt anders gemacht.

![bildschirmfoto 2015-04-03 um 22 00 48](https://cloud.githubusercontent.com/assets/3239082/6987971/20e5c6a2-da4d-11e4-972c-f4b24e7a65c9.png)

**Comment by eazyliving** [comment]
Ich bin mir nicht im Klaren, wie das wirklich gehen soll... Und Weiterleitungen im _GET mitgeben ist auch so eher mau... :)

Ich sehe hier zwei Punkte: Search als Extension (muss ich ggf noch mal in mich gehen) und dann das RETURN. Wenn ich heute Abend nen Ruhigen schieben kann, fällt mir vll was dazu ein.

**Comment by eazyliving** [comment]
So. Wenn ich das mit der Extension vom @McCouman recht sehe, ist das Thema gegessen, wa?
