### ISSUE TITLE
Designvorschlag Subscribe Button

### ISSUE THREAD

**Issue by i42n** [eazyliving/firtz#99]
Was haltet ihr von der Idee den Subscribe Button noch als "dicken großen Button" in der Sidebar unter das Podcast Logo zu packen? Wäre präsenter als nur oben in der Menubar.

**Comment by McCouman** [comment]
Sehe ich eben so. 

Im Menü würde ich den eventuell sogar ganz heraus nehmen außer im mobile View. 

Jedoch gibt es einige, die nicht viele statische Seiten haben und das sieht das wiederum sehr unschön aus.

**Comment by eazyliving** [comment]
Nein, im Standardtheme möchte ich das schon ober im Menü haben. Ich hasse es wirklich zutiefst, ewig scrollen zu müssen, um den Feed zu finden. Das geht über-haupt nicht :)

Einen Button in der Seitenleiste: vielleicht. 

Worüber ich lieber reden würde: Durch welchen Begriff könnten wir das "Abonnieren" ersetzen? Dieses Wort ist mMn negativ oder zumindest problematisch belegt. "Abo"->"Bindung"->"Geld"? Ihr wisst sicher, was ich meine.

**Comment by i42n** [comment]
Was ich mir als "mobile" View auf die Seite gut vorstellen könnt:

Seite:
------------------
Logo
Podcastname
Subscribe Button

Podlove Player zu je den 2 neusten Folgen
-------------------

So, dass die Landing Page im mobile View irgendwie direkter auf das Abo hinweist. Ich rufe häufig Podcast Webseiten auf dem Smartphone auf, um irgendwie zu abonnieren. Da muss ich dann häufig bis in den Footer scrollen um den fast verstecken Feed zu finden.

Zum "Abo" Begriff: Da hast du Recht @eazyliving. Der Begriff ist wirklich nicht optimal, wenn man sich nicht mit Podcasts auskennt. Allerdings denke ich auch, dass der schon recht etabliert ist. Von Youtube kennen das viele ja auch, dort heißt es genauso.

**Comment by eazyliving** [comment]
Was ich ja gerne hätte (ist das hier ein Wunschkonzert? ;)): Eine extrem reduzierte Variante. So reduziert, dass man nur folgendes sieht:

Kopf (mit Menu-Aufklappbutton), darunter für jede Episode (10 Stück von mir aus) eine ca. 1cm hohe Leiste mit Titel, Datum und einem nackten Playbutton). Kein Kram, kein nix, im Grunde reines Playing.

**Comment by McCouman** [comment]
In übrigen habe ich am PSB geschraubt und das Design ein wenig angepasst.
Ist jetzt Flacher und weniger abgerundet.
Im Phone-View wird nun der gesamte Bildschirm genutzt, hingegen der Tablet und Desktop als alert Box kommt.

![bildschirmfoto 2015-04-04 um 14 53 37](https://cloud.githubusercontent.com/assets/3239082/6992713/29965bd4-dadb-11e4-8340-328c08963876.png)

**Comment by eazyliving** [comment]
Großartig! Das Original des Buttons passt in keine Gestaltung hinein und kratzt mich im Auge. So ist das doch deutlich angenehmer. Danke!

**Comment by McCouman** [comment]
Sehe ich auch so :)

**Comment by i42n** [comment]
Sieht toll aus! Aber das musst du dann jedes Mal anpassen, wenn es ein Update für den Subscribe Button gibt oder?

**Comment by McCouman** [comment]
Denke schon, außer Sie übernehmen den style :P

**Comment by i42n** [comment]
Freue mich auf den Pull-Request hier rein!

**Comment by McCouman** [comment]
<pre>eazyliving commented 9 days ago
Was ich ja gerne hätte (ist das hier ein Wunschkonzert? ;)): Eine extrem reduzierte Variante. So reduziert, dass man nur folgendes sieht:

Kopf (mit Menu-Aufklappbutton), darunter für jede Episode (10 Stück von mir aus) eine ca. 1cm hohe Leiste mit Titel, Datum und einem nackten Playbutton). Kein Kram, kein nix, im Grunde reines Playing.</pre>

Meines Erachtens ist das eine Web-App und genau daran arbeite ich noch nebenbei. Da bin ich mir noch nicht sicher wie ich das in Firtz einbinden kann. Kommt später, wenn ich weis, wie ich das mit den Extensions "zeugs" so bauen kann. Da ich PHP benötige für den Header-Type. Sowas habe ich späterererer auch für Podbe geplant. Dort aber schon getestet :)

**Comment by McCouman** [comment]
Hier mal die Methode für die Extension:

<pre>
function find_mobile_browser() {
     if(preg_match('/(iphone|ipad|ipod|alcatel|android|blackberry|benq|cell|elaine|htc|iemobile|j2me|java|midp|mini|mobi|motorola|nokia|palm|panasonic|philips|phone|sagem|sharp|smartphone|sony|symbian|t-mobile|up\.browser|up\.link|vodafone|wap|wireless|xda|zte)/i', $_SERVER['HTTP_USER_AGENT'])) {
        return true;
    } else {
        return false;
    }
}
</pre>

Und hier die Abfrage:
<pre>
$mobile_browser = find_mobile_browser(); 
if($mobile_browser) { 
    echo "Hallo Handy"; // Wenn mobile Browser gefunden, dann tue dies 
} else { 
    echo "Hallo PC"; // Ansonsten tue das
}
</pre>

Wenn dir da was einfällt? Ich bin mir da recht unsicher, da die Seite ja geparst wird und gecached.
Daher wird es sicher ein Problem geben, wenn man es in die site html mittels: 
<code>&lt;check if="{{@templatevars.mobile == 'on'}}">...&lt;/check></code>
Da dann sicher der eigentliche Check nicht funktioniert. Es ist ja theoretisch ein Art "Weiterleitung".

Wenn man also zum Beispiel: statt "show": 
<code>http://news.podbe.de/neuigkeiten/show</code> 

auf "mobile" weiterleitet (?)
<code>http://news.podbe.de/neuigkeiten/mobile</code> 

und mobile dann die Datei mobile.html statt der site.html nutzen würde. wäre das sicher möglich.
Jedoch sollte es nur über eine Extension möglich sein, den mobile View auch zu nutzen.

**Comment by eazyliving** [comment]
Das ist ja eine grundsätzliche Frage. Betrachte ich diesen Webapp/mobile-View als eigenständige Anwendunge (Extension) oder als responsive Gestaltung der site.html...

Ich könnte mir durchaus beides vorstellen, wobei responsive hier in der Schere weit auseinandergehen würde zum default view (desktop). Einfacher wird's mit der Extension. Und dann braucht man da im Grunde gar keine Abfrage nach mobile/nicht mobile machen. Da ist's dann so und basta. Die Extension würde dann schlicht /mobile ans Ende der URL werfen und dann den reduzierten view ausgeben, egal ob auf Smartphone, Tablet oder Desktop.
